-- updating for github.com/cmangos/classic-db

-- 1807_dungeons_texts.sql
UPDATE `locales_npc_text` SET 
	`Text0_0_loc8`='Недавно друид из ночных эльфов по имени Наралекс обнаружил сеть подземных пещер в самом сердце Степей. Названные пещерами Стенаний, эти природные пещеры имели множество расщелин, заполненных паром, которые производили длинный, скорбный звук на выходе. Он верил, что может использовать родники в этих пещерах, чтобы вернуть земле Степей былое плодородие, но для этого потребовалось бы перенаправить энергию из легендарного Изумрудного сна. Однажды, пребывая во сне, его видения обернулись ночными кошмарами. Вскоре, пещеры Стенаний начали меняться, воды стали отвратительными, а некогда миролюбивые существа превратились в злобных, смертоносных хищников. Говорят, что где-то в сердце лабиринта таится и сам Наралекс, плененный в Изумрудном сне. Его кошмар наяву поработил даже его верных сподвижников, и они обратились в злобных Друидов Клыка.', 
	`Text0_1_loc8`='Недавно друид из ночных эльфов по имени Наралекс обнаружил сеть подземных пещер в самом сердце Степей. Названные пещерами Стенаний, эти природные пещеры имели множество расщелин, заполненных паром, которые производили длинный, скорбный звук на выходе. Он верил, что может использовать родники в этих пещерах, чтобы вернуть земле Степей былое плодородие, но для этого потребовалось бы перенаправить энергию из легендарного Изумрудного сна. Однажды, пребывая во сне, его видения обернулись ночными кошмарами. Вскоре, пещеры Стенаний начали меняться, воды стали отвратительными, а некогда миролюбивые существа превратились в злобных, смертоносных хищников. Говорят, что где-то в сердце лабиринта таится и сам Наралекс, плененный в Изумрудном сне. Его кошмар наяву поработил даже его верных сподвижников, и они обратились в злобных Друидов Клыка.' 
WHERE `entry` = 7183;


-- 1809_page_text.sql
DELETE FROM locales_page_text WHERE entry IN (2930, 2931, 2932, 2933, 2934);


-- 1805_z2706_01_mangos_dbscript_string_rename.sql
UPDATE `dbscript_string` SET `content_loc8`='Спасибо, $N. Удачи вам.' WHERE `entry` = 2000000000;
UPDATE `dbscript_string` SET `content_loc8`='Скалистый водопад лежит вдоль гор на северо-востоке.' WHERE `entry` = 2000000001;
UPDATE `dbscript_string` SET `content_loc8`='Отправляйся немедленно, $N. Моя судьба в твоих руках.' WHERE `entry` = 2000000002;
UPDATE `dbscript_string` SET `content_loc8`='%s показывает на кувшин с водой, сидя на краю скважины.' WHERE `entry` = 2000000003;
UPDATE `dbscript_string` SET `content_loc8`='Прошло много времени, Бетор, друг мой.' WHERE `entry` = 2000000004;
UPDATE `dbscript_string` SET `content_loc8`='Когда позволит время, мы поговорим дольше. Так как нам есть что обсудить.' WHERE `entry` = 2000000005;
UPDATE `dbscript_string` SET `content_loc8`='И спасибо тебе, $N. Без твоей помощи, я бы никогда встал на свой путь... путь Отрекшихся.' WHERE `entry` = 2000000006;
UPDATE `dbscript_string` SET `content_loc8`='Прощай, мой друг.' WHERE `entry` = 2000000007;
UPDATE `dbscript_string` SET `content_loc8`='%s нюхает эликсир, затем нетерпеливо зарываться!' WHERE `entry` = 2000000008;
UPDATE `dbscript_string` SET `content_loc8`='Что случилось?' WHERE `entry` = 2000000009;
UPDATE `dbscript_string` SET `content_loc8`='Волкору нужна помощь?' WHERE `entry` = 2000000010;
UPDATE `dbscript_string` SET `content_loc8`='Хорошо, я найду людей что бы помочь ему.' WHERE `entry` = 2000000011;
UPDATE `dbscript_string` SET `content_loc8`='О, конечно надо выпить! Я, пожалуй, опрокину еще кружку... присмотришь за моими бочками, $N?' WHERE `entry` = 2000000012;
UPDATE `dbscript_string` SET `content_loc8`='Как проходит наблюдение за бочками...?' WHERE `entry` = 2000000013;
UPDATE `dbscript_string` SET `content_loc8`='Ну, пора возвращаться к своим делам. Было так приятно взять небольшой перерыв и выпить немного громового эля!' WHERE `entry` = 2000000014;
UPDATE `dbscript_string` SET `content_loc8`='Я и мой брат благодарим тебя $n.' WHERE `entry` = 2000000016;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает воспевать о камне у источника и пламени костра.' WHERE `entry` = 2000000017;
UPDATE `dbscript_string` SET `content_loc8`='Вода Провидцев готова к употреблению, $N.' WHERE `entry` = 2000000018;
UPDATE `dbscript_string` SET `content_loc8`='Будьте терпеливы $N. Факел почти зажжен.' WHERE `entry` = 2000000019;
UPDATE `dbscript_string` SET `content_loc8`='Это интересно...' WHERE `entry` = 2000000020;
UPDATE `dbscript_string` SET `content_loc8`='Я должен проконсультироваться с Норамом и Горацием.' WHERE `entry` = 2000000021;
UPDATE `dbscript_string` SET `content_loc8`='Иди же, $N. Найди Волкора... и помни, магия защищает тебя до тех пор, пока ты с кем-нибудь не заговоришь.' WHERE `entry` = 2000000022;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает применять заклинание после того, как вы сняли с него плащ.' WHERE `entry` = 2000000023;
UPDATE `dbscript_string` SET `content_loc8`='Я... я... чувствую... себя... не хорошо...' WHERE `entry` = 2000000024;
UPDATE `dbscript_string` SET `content_loc8`='Мой разум... моя плоть... я... гнию!' WHERE `entry` = 2000000025;
UPDATE `dbscript_string` SET `content_loc8`='Ой!' WHERE `entry` = 2000000026;
UPDATE `dbscript_string` SET `content_loc8`='Люди Западного края поприветствуйте $N, $gхраброго и отважного защитника:храбрую и отважную защитницу; свободы.' WHERE `entry` = 2000000028;
UPDATE `dbscript_string` SET `content_loc8`='Следуйте за, $N. Я скоро начну призыв...' WHERE `entry` = 2000000029;
UPDATE `dbscript_string` SET `content_loc8`='Это имеет смысл!' WHERE `entry` = 2000000030;
UPDATE `dbscript_string` SET `content_loc8`='Осторожнее, $n! Посмотри на запад!' WHERE `entry` = 2000000031;
UPDATE `dbscript_string` SET `content_loc8`='Приготовься $N, демон в этом шаре это зверь скверны.' WHERE `entry` = 2000000032;
UPDATE `dbscript_string` SET `content_loc8`='%s призывает гонца...' WHERE `entry` = 2000000033;
UPDATE `dbscript_string` SET `content_loc8`='Позволь мне помочь тебе.' WHERE `entry` = 2000000034;
UPDATE `dbscript_string` SET `content_loc8`='Выпей это, оно поможет.' WHERE `entry` = 2000000035;
UPDATE `dbscript_string` SET `content_loc8`='Ты будешь в порядке.' WHERE `entry` = 2000000036;
UPDATE `dbscript_string` SET `content_loc8`='Пока мы не встретимся снова, будьте храбры.' WHERE `entry` = 2000000042;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает призыв...' WHERE `entry` = 2000000043;
UPDATE `dbscript_string` SET `content_loc8`='Это все...' WHERE `entry` = 2000000044;
UPDATE `dbscript_string` SET `content_loc8`='Нет ничего лучше жгучей бражки холодным утром в Дун Мороге!' WHERE `entry` = 2000000045;
UPDATE `dbscript_string` SET `content_loc8`='O-o-o-o-o, горячо, горячо, горячо! Ну, я не знаю, что может поднять тебя на ноги, если не это!' WHERE `entry` = 2000000046;
UPDATE `dbscript_string` SET `content_loc8`='Ква! Нет!!! Этого не может... ква... быть! Обманули меня... ква... мерзкие ква-ри! Ква!' WHERE `entry` = 2000000047;
UPDATE `dbscript_string` SET `content_loc8`='Теперь давайте поместим эту редкую землю в мой горшок...' WHERE `entry` = 2000000048;
UPDATE `dbscript_string` SET `content_loc8`='Еще раз спасибо, $N. Эта редкая земля будет очень полезна в моих экспериментах.' WHERE `entry` = 2000000049;
UPDATE `dbscript_string` SET `content_loc8`='Эй там, Белм! Дайте мне кружку Громового эля, и еще одну для моего хорошего друга $N!' WHERE `entry` = 2000000056;
UPDATE `dbscript_string` SET `content_loc8`='Духи воды, взываю к вам и молю вас о помощи! $N $gобратился:обратилась; к вам с просьбой – и я верю, что $gего:ее; намерения были благородны. Пожалуйста, помогите нам.' WHERE `entry` = 2000000057;
UPDATE `dbscript_string` SET `content_loc8`='Благодарю тебя, великий дух. Спасибо тебе!' WHERE `entry` = 2000000058;
UPDATE `dbscript_string` SET `content_loc8`='Можешь идти, $N.' WHERE `entry` = 2000000059;
UPDATE `dbscript_string` SET `content_loc8`='Следуйте за мной, хороший $C. Я сделаю ваш чепрак быстрее, чем смог бы выпить залпом Дворфийский портер. Ммммм... портер.' WHERE `entry` = 2000000063;
UPDATE `dbscript_string` SET `content_loc8`='Хорошо, это должно завершиться. Ну-ка, назад к магазину, закончим наши дела!' WHERE `entry` = 2000000064;
UPDATE `dbscript_string` SET `content_loc8`='Мы не потерпим на нашей земле слуг демонов!' WHERE `entry` = 2000000065;
UPDATE `dbscript_string` SET `content_loc8`='Мир и терпение будет с вами, $N. Будьте всегда сильным.' WHERE `entry` = 2000000066;
UPDATE `dbscript_string` SET `content_loc8`='%s пытается вскрыть деревянную ногу Моури...' WHERE `entry` = 2000000067;
UPDATE `dbscript_string` SET `content_loc8`='Вот еще! $N, эта нога не сдвинется с места!' WHERE `entry` = 2000000068;
UPDATE `dbscript_string` SET `content_loc8`='Спасибо, $N.' WHERE `entry` = 2000000069;
UPDATE `dbscript_string` SET `content_loc8`='Я уверен что смогу найти применение этой микстуре...' WHERE `entry` = 2000000070;
UPDATE `dbscript_string` SET `content_loc8`='Еще раз спасибо за помощь. Пусть ваш ветер всегда будет попутным.' WHERE `entry` = 2000000071;
UPDATE `dbscript_string` SET `content_loc8`='Проще чем я ожидал... печать Торадина снова цела.' WHERE `entry` = 2000000072;
UPDATE `dbscript_string` SET `content_loc8`='Подождите, $N!!! Похоже, что здесь нам понадобится дополнительная помощь...' WHERE `entry` = 2000000073;
UPDATE `dbscript_string` SET `content_loc8`='В коробку, мои красотульки! Так, так. Одна за другой, поскакали!' WHERE `entry` = 2000000074;
UPDATE `dbscript_string` SET `content_loc8`='Слушайте, жители Танариса! Позвольте представить $gизвестного:известную; $n, $gявляющегося:являющуюся; превосходным членом Ордена Мифрила. Кузнец чести, преданности и бесконечного терпения. Три ура за $n!' WHERE `entry` = 2000000076;
UPDATE `dbscript_string` SET `content_loc8`='%s наблюдает затем, как течет его кровь, и коварство ящера пронизывает него.' WHERE `entry` = 2000000077;
UPDATE `dbscript_string` SET `content_loc8`='Что это за сила, которая пронизывает меня? Действительно ли это сила шаманства, о которой говорил Тор\'ган... ?' WHERE `entry` = 2000000078;
UPDATE `dbscript_string` SET `content_loc8`='Удивительно! Я чувствую... возобновленным. Мои силы возвращаются!' WHERE `entry` = 2000000079;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает обряд создания...' WHERE `entry` = 2000000080;
UPDATE `dbscript_string` SET `content_loc8`='Я создал тотем. Теперь, $N, ты $gдолжен:должна; очистить колодец.' WHERE `entry` = 2000000081;
UPDATE `dbscript_string` SET `content_loc8`='%s создает новый тотем...' WHERE `entry` = 2000000082;
UPDATE `dbscript_string` SET `content_loc8`='Тотем готов, $N.' WHERE `entry` = 2000000083;
UPDATE `dbscript_string` SET `content_loc8`='%s преобразовывает предметы $N и преподносит их тотему очищению...' WHERE `entry` = 2000000084;
UPDATE `dbscript_string` SET `content_loc8`='Тотем готов. Колодец теперь может быть очищен.' WHERE `entry` = 2000000085;
UPDATE `dbscript_string` SET `content_loc8`='%s изучает пергамент из сумеречного фолианта...' WHERE `entry` = 2000000086;
UPDATE `dbscript_string` SET `content_loc8`='%s поражен безудержной магией!' WHERE `entry` = 2000000087;
UPDATE `dbscript_string` SET `content_loc8`='Хм...' WHERE `entry` = 2000000088;
UPDATE `dbscript_string` SET `content_loc8`='Духи Когтистых гор все еще разгневаны, $N.' WHERE `entry` = 2000000089;
UPDATE `dbscript_string` SET `content_loc8`='Боюсь, что нам никогда не удастся успокоить их...' WHERE `entry` = 2000000090;
UPDATE `dbscript_string` SET `content_loc8`='%s выслушивает просьбу $N.' WHERE `entry` = 2000000091;
UPDATE `dbscript_string` SET `content_loc8`='Вы сделали правильно, что пришли. Моя мудрость будет вашей.' WHERE `entry` = 2000000092;
UPDATE `dbscript_string` SET `content_loc8`='Иди, слуга. Передай мои слова аптекарю Заме.' WHERE `entry` = 2000000093;
UPDATE `dbscript_string` SET `content_loc8`='%s передает сообщение аптекарю Заме.' WHERE `entry` = 2000000094;
UPDATE `dbscript_string` SET `content_loc8`='%s улыбается.' WHERE `entry` = 2000000095;
UPDATE `dbscript_string` SET `content_loc8`='%s создает токсин...' WHERE `entry` = 2000000096;
UPDATE `dbscript_string` SET `content_loc8`='Вот и все, $N. Токсин готов.' WHERE `entry` = 2000000097;
UPDATE `dbscript_string` SET `content_loc8`='%s заполняет контейнер токсином.' WHERE `entry` = 2000000098;
UPDATE `dbscript_string` SET `content_loc8`='Токсин готов, $N.' WHERE `entry` = 2000000099;
UPDATE `dbscript_string` SET `content_loc8`='%s ставит ящик с деталями на землю.' WHERE `entry` = 2000000100;
UPDATE `dbscript_string` SET `content_loc8`='%s хватает деталь и кладет ее в свой карман...' WHERE `entry` = 2000000101;
UPDATE `dbscript_string` SET `content_loc8`='Вот, нужно сделать это...' WHERE `entry` = 2000000102;
UPDATE `dbscript_string` SET `content_loc8`='%s вдыхает своим носом щепотку сонной пыли...' WHERE `entry` = 2000000103;
UPDATE `dbscript_string` SET `content_loc8`='%s ошеломлен...' WHERE `entry` = 2000000104;
UPDATE `dbscript_string` SET `content_loc8`='АПЧХИ!' WHERE `entry` = 2000000105;
UPDATE `dbscript_string` SET `content_loc8`='Ничего себе! $N, эта сонная пыль очень сильная штука!' WHERE `entry` = 2000000106;
UPDATE `dbscript_string` SET `content_loc8`='Эй, $N! Не забудь захватить ящик, справочник и палочку-погонялочку!' WHERE `entry` = 2000000107;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает танцевать.' WHERE `entry` = 2000000108;
UPDATE `dbscript_string` SET `content_loc8`='Ха-ха! $N, ты отличный партнер!' WHERE `entry` = 2000000109;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает применять заклинание на сердце и косноязычие.' WHERE `entry` = 2000000110;
UPDATE `dbscript_string` SET `content_loc8`='Выводок Ониксии!' WHERE `entry` = 2000000111;
UPDATE `dbscript_string` SET `content_loc8`='Хорошо, команда. Приступим к работе по установке этих костей.' WHERE `entry` = 2000000112;
UPDATE `dbscript_string` SET `content_loc8`='Сыворотка будет готова через несколько минут, $N.' WHERE `entry` = 2000000113;
UPDATE `dbscript_string` SET `content_loc8`='Почти готово...' WHERE `entry` = 2000000114;
UPDATE `dbscript_string` SET `content_loc8`='Сыворотка готова, $N. Теперь, подойди. Нам нужно поговорить.' WHERE `entry` = 2000000115;
UPDATE `dbscript_string` SET `content_loc8`='%s делает большой глоток эля.' WHERE `entry` = 2000000116;
UPDATE `dbscript_string` SET `content_loc8`='Это было освежающе. А теперь то, что нужно рассказать...' WHERE `entry` = 2000000117;
UPDATE `dbscript_string` SET `content_loc8`='Я считаю, что Отрекшиеся обманывают союзников Орды... подожди... я чувствую... головокружение...' WHERE `entry` = 2000000118;
UPDATE `dbscript_string` SET `content_loc8`='%s корчится от боли.' WHERE `entry` = 2000000119;
UPDATE `dbscript_string` SET `content_loc8`='AAAAAAAAAAAAAAAAРГХ!' WHERE `entry` = 2000000120;
UPDATE `dbscript_string` SET `content_loc8`='Я уничтожу эти инструменты зла! За Орду!' WHERE `entry` = 2000000121;
UPDATE `dbscript_string` SET `content_loc8`='Пожалуйста, следуй за мной.' WHERE `entry` = 2000000122;
UPDATE `dbscript_string` SET `content_loc8`='Я действительно не выяснила, что там такое, но есть кое-что странное в этих горячих источниках...' WHERE `entry` = 2000000123;
UPDATE `dbscript_string` SET `content_loc8`='%s бросает меч в неглубокий водоем.' WHERE `entry` = 2000000124;
UPDATE `dbscript_string` SET `content_loc8`='Я обнаружила, что, когда я бросаю что-то в эту воду, а затем вынимаю, оно становится значительно лучше.' WHERE `entry` = 2000000125;
UPDATE `dbscript_string` SET `content_loc8`='Хорошо, что бы это не было, оно действительно работает!' WHERE `entry` = 2000000126;
UPDATE `dbscript_string` SET `content_loc8`='И я настроена, узнать больше... Так что, если тебе понадобится моя помощь, ты знаешь, где меня найти.' WHERE `entry` = 2000000127;
UPDATE `dbscript_string` SET `content_loc8`='Чествуйте своих героев! Сегодня они нанесли сокрушающий удар нашим самым ненавистным врагам! Самозванец Ренд Чернорук мертв!' WHERE `entry` = 2000000128;
UPDATE `dbscript_string` SET `content_loc8`='Вдохновитесь моей мощью! Наполнитесь моей силой и сражайтесь во славу Орды!' WHERE `entry` = 2000000129;
UPDATE `dbscript_string` SET `content_loc8`='Документы мои, братья!' WHERE `entry` = 2000000130;
UPDATE `dbscript_string` SET `content_loc8`='Ох, я думал что уже мертв. Ой... до сих пор кружится в голове...' WHERE `entry` = 2000000131;
UPDATE `dbscript_string` SET `content_loc8`='Думаю, что теперь я смогу вернуться в крепость. И кем бы вы небыли... спасибо. Да благословит вас Элуна!' WHERE `entry` = 2000000132;
UPDATE `dbscript_string` SET `content_loc8`='Это не должно занять много времени...' WHERE `entry` = 2000000133;
UPDATE `dbscript_string` SET `content_loc8`='Напиток невидимости готов, $n.' WHERE `entry` = 2000000134;
UPDATE `dbscript_string` SET `content_loc8`='Здесь ничего нет...' WHERE `entry` = 2000000135;
UPDATE `dbscript_string` SET `content_loc8`='Корбетт, дорогой. Харлану нужна целая куча вязаных рубашек и штанов – чем скорее, тем лучше.' WHERE `entry` = 2000000139;
UPDATE `dbscript_string` SET `content_loc8`='Корбетт, ты здесь? Харлану нужна еще одна партия вязаных товаров. Ты можешь отнести ему это?' WHERE `entry` = 2000000140;
UPDATE `dbscript_string` SET `content_loc8`='Разумеется, сладость моя. Я скоро вернусь...' WHERE `entry` = 2000000141;
UPDATE `dbscript_string` SET `content_loc8`='Я отнесу ему это прямо сейчас!' WHERE `entry` = 2000000142;
UPDATE `dbscript_string` SET `content_loc8`='Хм... Как закончим, я схожу в ту сырную лавку и перекушу.' WHERE `entry` = 2000000143;
UPDATE `dbscript_string` SET `content_loc8`='Возможно, я смогу получить с этой сделки несколько дополнительных монет. И может смогу купить себе обед...' WHERE `entry` = 2000000144;
UPDATE `dbscript_string` SET `content_loc8`='Эй, Харлан. Вот партия вязаных тканей.' WHERE `entry` = 2000000145;
UPDATE `dbscript_string` SET `content_loc8`='Уфф! Вот еще товары, Харлан. Быстро, поди, расходятся?' WHERE `entry` = 2000000146;
UPDATE `dbscript_string` SET `content_loc8`='Ах да, и быстро доставлено. Как всегда, приятное иметь дело с вами, Корбетт.' WHERE `entry` = 2000000147;
UPDATE `dbscript_string` SET `content_loc8`='А, очень вам признателен, Корбетт. Мы пустим их в дело прямо сейчас.' WHERE `entry` = 2000000148;
UPDATE `dbscript_string` SET `content_loc8`='Приятно видеть, что у вас все хорошо, Харлан. Надеюсь, мы скоро увидимся?' WHERE `entry` = 2000000149;
UPDATE `dbscript_string` SET `content_loc8`='Что ж, тогда у меня все. Удачи, Харлан.' WHERE `entry` = 2000000150;
UPDATE `dbscript_string` SET `content_loc8`='А теперь закусим...' WHERE `entry` = 2000000151;
UPDATE `dbscript_string` SET `content_loc8`='Приветствую семью Триас! Мне головку сыра, пожалуйста!' WHERE `entry` = 2000000152;
UPDATE `dbscript_string` SET `content_loc8`='Добрый день, Иллинг! Привет, Элайна! Можно мне головку сыра, а?' WHERE `entry` = 2000000153;
UPDATE `dbscript_string` SET `content_loc8`='Добрый день, Корбетт. Вот ваш сыр, свежий, сделанный этим утром! Как дела в вашем магазине?' WHERE `entry` = 2000000154;
UPDATE `dbscript_string` SET `content_loc8`='Эй, Корбетт! Вот ты где! Как там твоя протяжная мастерская? Все так же процветает?' WHERE `entry` = 2000000155;
UPDATE `dbscript_string` SET `content_loc8`='Да, мэм, дело быстрое!' WHERE `entry` = 2000000156;
UPDATE `dbscript_string` SET `content_loc8`='Большое тебе спасибо!' WHERE `entry` = 2000000157;
UPDATE `dbscript_string` SET `content_loc8`='Пора вернуться в лавку...' WHERE `entry` = 2000000158;
UPDATE `dbscript_string` SET `content_loc8`='Вот и я!' WHERE `entry` = 2000000159;
UPDATE `dbscript_string` SET `content_loc8`='Ma reth bromo zoln kilagrin dra ma zoern tu ko fraht ka tadrom Ma krin drinor zaln dirnor Ma krin kan aasrugel korsul' WHERE `entry` = 2000000160;
UPDATE `dbscript_string` SET `content_loc8`='Р-Р-Р-Р-Р!' WHERE `entry` = 2000000161;
UPDATE `dbscript_string` SET `content_loc8`='ТЕМНОЛЕСЬЕ... ХОЧУ ЕСТЬ!' WHERE `entry` = 2000000162;
UPDATE `dbscript_string` SET `content_loc8`='Я сказал ХОРОШИЙ ДЕНЬ!' WHERE `entry` = 2000000163;
UPDATE `dbscript_string` SET `content_loc8`='Мой меч Принцип хорошо служил мне при жизни. Но, поскольку дух мой может теперь покинуть юдоль скорби, Принцип мне больше не нужен.' WHERE `entry` = 2000000164;
UPDATE `dbscript_string` SET `content_loc8`='Я не предам любовь моей дочери и буду надеяться, что Свет простит мне мои грехи.' WHERE `entry` = 2000000165;
UPDATE `dbscript_string` SET `content_loc8`='О НЕТ! Король умер! Э... Да здравствует король! Да!' WHERE `entry` = 2000000166;
UPDATE `dbscript_string` SET `content_loc8`='Ага, он мертвее мертвого. Ты теперь, значит, $gновый король:новая королева;, тебе вся власть! Гордок отныне твой, $gхозяин:госпожа;! Ты поговори со мной – узнаешь, как здесь править! Я был... и есть помощник короля! Не зря меня зовут Хитрюгой!' WHERE `entry` = 2000000167;
UPDATE `dbscript_string` SET `content_loc8`='% смотрит на северо-запад и издает длинный, низкий вой.' WHERE `entry` = 2000000168;
UPDATE `dbscript_string` SET `content_loc8`='%s издает могучий вой.' WHERE `entry` = 2000000169;
UPDATE `dbscript_string` SET `content_loc8`='По вашей команде!' WHERE `entry` = 2000000170;
UPDATE `dbscript_string` SET `content_loc8`='Жди здесь, $N. Робот-шпион заставит Лесковара выйти как можно скорее. Приготовься! Атакуй только после того как подслушаешь их разговор.' WHERE `entry` = 2000000171;
UPDATE `dbscript_string` SET `content_loc8`='Приветствую вас. Я бы хотела поговорить с лордом Лесковаром.' WHERE `entry` = 2000000172;
UPDATE `dbscript_string` SET `content_loc8`='Конечно. Он ждет вас в библиотеке.' WHERE `entry` = 2000000173;
UPDATE `dbscript_string` SET `content_loc8`='Спасибо. Да прибудет с вами Свет.' WHERE `entry` = 2000000174;
UPDATE `dbscript_string` SET `content_loc8`='Милорд, ваш гость прибыл. Он ожидает вас.' WHERE `entry` = 2000000175;
UPDATE `dbscript_string` SET `content_loc8`='Ох, благодарю. Я оставлю вас в библиотеке, мне нужно решить один маленький вопрос.' WHERE `entry` = 2000000176;
UPDATE `dbscript_string` SET `content_loc8`='Я использую это время с мудростью, милорд. Спасибо.' WHERE `entry` = 2000000177;
UPDATE `dbscript_string` SET `content_loc8`='Я хочу погрузиться в медитацию, оставьте меня.' WHERE `entry` = 2000000178;
UPDATE `dbscript_string` SET `content_loc8`='Да, сэр!' WHERE `entry` = 2000000179;
UPDATE `dbscript_string` SET `content_loc8`='%s ждет, пока скроется стража.' WHERE `entry` = 2000000180;
UPDATE `dbscript_string` SET `content_loc8`='А вот и ты. Какие новости из Западного Края?' WHERE `entry` = 2000000181;
UPDATE `dbscript_string` SET `content_loc8`='Ван Клиф передает, что все идет по плану. Но до него дошли слухи, что кто-то ведет слежку.' WHERE `entry` = 2000000182;
UPDATE `dbscript_string` SET `content_loc8`='Хм, возможно это был надоедливый Шоу. Посмотрим, что мне удастся выяснить. Я свяжусь с тобой в ближайшее время.' WHERE `entry` = 2000000183;
UPDATE `dbscript_string` SET `content_loc8`='Хорошо. Тогда я возвращаюсь.' WHERE `entry` = 2000000184;
UPDATE `dbscript_string` SET `content_loc8`='Вот и все! Это то, чего мы ждали! Убейте их!' WHERE `entry` = 2000000185;
UPDATE `dbscript_string` SET `content_loc8`='Защищайся!' WHERE `entry` = 2000000186;
UPDATE `dbscript_string` SET `content_loc8`='Поганище пересекло лагерь Ночного дозора! Быстрее, мы должны перехватить его, прежде чем он достигнет города!' WHERE `entry` = 2000000187;
UPDATE `dbscript_string` SET `content_loc8`='Чудовище повержено! В Темнолесье все спокойно!' WHERE `entry` = 2000000188;
UPDATE `dbscript_string` SET `content_loc8`='Потроха иглогривов! Это должно помочь. Рыба обожает иглогривов.' WHERE `entry` = 2000000189;
UPDATE `dbscript_string` SET `content_loc8`='Поймал! Интересно, кто-нибудь из стражей проголодался? Идем, Клык!' WHERE `entry` = 2000000190;
UPDATE `dbscript_string` SET `content_loc8`='Если вы проголодались, у меня есть рыба...' WHERE `entry` = 2000000191;
UPDATE `dbscript_string` SET `content_loc8`='Да, это хорошая добыча! Ты принес Орде славу, мальчик, спасибо тебе!' WHERE `entry` = 2000000192;
UPDATE `dbscript_string` SET `content_loc8`='Как пожелаешь...' WHERE `entry` = 2000000195;
UPDATE `dbscript_string` SET `content_loc8`='Я сильно сомневаюсь, что нам есть о чем говорить, $gстранник:странница;...' WHERE `entry` = 2000000196;
UPDATE `dbscript_string` SET `content_loc8`='Лично я ничего против не имею. В конце концов, этого высшего эльфа пустил сюда сам принц – не мне обсуждать его решения. К чести этого принца, он не сразу решил сжигать господина Винтхалуса.' WHERE `entry` = 2000000197;
UPDATE `dbscript_string` SET `content_loc8`='Не стоит сейчас обращаться к нам, $gстранник:странница;. Возвращайся к тем, кто послал тебя на поиски потерянного мастера и сообщи им, что тебе ничего не удалось найти. Когда это будет сделано, и я узнаю об этом, возвращайся и я открою тебе тайны умершего.' WHERE `entry` = 2000000198;
UPDATE `dbscript_string` SET `content_loc8`='Что? $N, вы мне верно служили, но...' WHERE `entry` = 2000000234;
UPDATE `dbscript_string` SET `content_loc8`='Зачем ты так рано $gпризвал:призвала; меня? Я еще не вошла в полную силу!' WHERE `entry` = 2000000235;
UPDATE `dbscript_string` SET `content_loc8`='Неважно. Ты $gбыл достаточно глуп:была достаточно глупа;, чтобы помочь мне, и теперь ты за это заплатишь!' WHERE `entry` = 2000000236;
UPDATE `dbscript_string` SET `content_loc8`='И еще раз спасибо, $n. А теперь я просто подожду здесь, пока можно будет безопасно уйти.' WHERE `entry` = 2000000237;
UPDATE `dbscript_string` SET `content_loc8`='Число моих сторонников уменьшается богиня, и моя собственная власть скоро будет недостаточна, чтобы держать в повиновении демонов Оскверненного леса.' WHERE `entry` = 2000000238;
UPDATE `dbscript_string` SET `content_loc8`='Богиня, дайте мне власть, чтобы победить моих врагов! Прошу вас услышьте, пожалуйста. Я весь в отчаянии!' WHERE `entry` = 2000000239;
UPDATE `dbscript_string` SET `content_loc8`='Что... что это? Может это ответ на мои просьбы? Элуна дала мне это оружие, эту косу, чтобы поразить демонов.' WHERE `entry` = 2000000240;
UPDATE `dbscript_string` SET `content_loc8`='Я потерпела неудачу... Я не выполнила свою обязанность... не выполнила долг по отношению к своему народу... Воргены напали, а коса моей богини утеряна.' WHERE `entry` = 2000000241;
UPDATE `dbscript_string` SET `content_loc8`='Это зло, что я впустила... В чьих руках находится теперь сила, что моя богиня подарила мне? Чья рука ее направляет?' WHERE `entry` = 2000000242;
UPDATE `dbscript_string` SET `content_loc8`='Терентис, Раэна отправила меня найти вас. Часовым Ясеневого леса нужна помощь.' WHERE `entry` = 2000000260;
UPDATE `dbscript_string` SET `content_loc8`='Сила Слезы Лун принадлежит мне!' WHERE `entry` = 2000000345;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает потирать Слезу Лун.' WHERE `entry` = 2000000346;
UPDATE `dbscript_string` SET `content_loc8`='Сила! Могущественная сила!' WHERE `entry` = 2000000347;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает издавать странные звуки. Слеза Лун падает на землю и разбивается.' WHERE `entry` = 2000000348;
UPDATE `dbscript_string` SET `content_loc8`='Подайте на помощь жертвам тяжелых времен! Подайте, пожалуйста!' WHERE `entry` = 2000000349;
UPDATE `dbscript_string` SET `content_loc8`='Помните о сиротах Штормграда!' WHERE `entry` = 2000000350;
UPDATE `dbscript_string` SET `content_loc8`='Делитесь своей добротой и золотом! Делитесь с детьми Штормграда, потерявшими родителей!' WHERE `entry` = 2000000351;
UPDATE `dbscript_string` SET `content_loc8`='Помогите детям Штормграда... жертвам войны и чумы!' WHERE `entry` = 2000000352;
UPDATE `dbscript_string` SET `content_loc8`='Давайте, $N. Озеро уже за поворотом.' WHERE `entry` = 2000000375;
UPDATE `dbscript_string` SET `content_loc8`='Встаньте рядом со мной, $N. Я защищу вас, если что-то пойдет не так.' WHERE `entry` = 2000000376;
UPDATE `dbscript_string` SET `content_loc8`='Малфурион!' WHERE `entry` = 2000000377;
UPDATE `dbscript_string` SET `content_loc8`='Ремул, друг мой. Я рад вновь увидеться с тобой. Я знал, что мое послание так или иначе найдет тебя.' WHERE `entry` = 2000000378;
UPDATE `dbscript_string` SET `content_loc8`='Я был во власти кошмаров, Малфурион. Что творится в Изумрудном Сне? В чем причина такой жестокости?' WHERE `entry` = 2000000379;
UPDATE `dbscript_string` SET `content_loc8`='Я боюсь худшего, старый друг. Во Сне мы сражались с новым врагом, порожденным древним злом. Благородный род Изеры пал жертвой старых слухов. Похоже, Кошмар прорвался сквозь барьер мира и ищет новую жертву в Азероте.' WHERE `entry` = 2000000380;
UPDATE `dbscript_string` SET `content_loc8`='Я чувствую это, Малфурион. Впереди тяжкие дни.' WHERE `entry` = 2000000381;
UPDATE `dbscript_string` SET `content_loc8`='Да, Ремул. Готовь смертных.' WHERE `entry` = 2000000382;
UPDATE `dbscript_string` SET `content_loc8`='Тебя не было слишком долго, Малфурион. Мир между детьми Азерота хрупок как никогда. А что с моим отцом? С твоим отцом? У тебя есть новости?' WHERE `entry` = 2000000383;
UPDATE `dbscript_string` SET `content_loc8`='Кенарий сражается на моей стороне. А Иллидан восседает на своем троне в Запределье, погрузившись в раздумья. Боюсь, что проигрыш Артасу окончательно сломил его, Ремул. Иллидана обуяло безумие. Он тысячу раз на дню прокручивает в голове ту битву, но в своих мыслях он побеждает, а поверженный Артас молит о пощаде. Вскоре нам, как братьям, выпадет еще одно испытание – но уже не такое, как было у колодца в Зин-Азшари.' WHERE `entry` = 2000000384;
UPDATE `dbscript_string` SET `content_loc8`='Ремул, меня тянет назад... Тиранда... передай, что я ее люблю... Скажи, что со мной все хорошо... Что я вернусь... Прощай!' WHERE `entry` = 2000000385;
UPDATE `dbscript_string` SET `content_loc8`='Прощай, старый друг... Прощай...' WHERE `entry` = 2000000386;
UPDATE `dbscript_string` SET `content_loc8`='Давай вернемся в рощу, $gсмертный:смертная;!' WHERE `entry` = 2000000387;
UPDATE `dbscript_string` SET `content_loc8`='Привет, Селарина. Боюсь, что сейчас я не смогу помочь тебе, но, возможно, здесь в Аубердине, кто-то из искателей приключений поможет...' WHERE `entry` = 2000000395;
UPDATE `dbscript_string` SET `content_loc8`='Спасибо, Терентис. Я останусь здесь настолько, насколько смогу.' WHERE `entry` = 2000000396;
UPDATE `dbscript_string` SET `content_loc8`='Надеюсь, мне удастся отправить достойную помощь Ясеневому лесу и часовым.' WHERE `entry` = 2000000397;
UPDATE `dbscript_string` SET `content_loc8`='Приготовиться! Зная, что мы живы, наги, не заставят себя долго ждать, чтобы показать свое преимущество.' WHERE `entry` = 2000000466;
UPDATE `dbscript_string` SET `content_loc8`='Опус хочет немного Золота Куэрго... с червем.' WHERE `entry` = 2000005001;
UPDATE `dbscript_string` SET `content_loc8`='Блестяшка потерялась! ЩЕЛК!! *кх*' WHERE `entry` = 2000005002;
UPDATE `dbscript_string` SET `content_loc8`='Киблер проводит расследование по Г.Е.Т.А.' WHERE `entry` = 2000005003;
UPDATE `dbscript_string` SET `content_loc8`='Блестяшка знает, где спрятаны сокровища.' WHERE `entry` = 2000005004;
UPDATE `dbscript_string` SET `content_loc8`='Драконы, контролируемые орками!? ЩЕЛК!' WHERE `entry` = 2000005005;
UPDATE `dbscript_string` SET `content_loc8`='Они все уходят в Пик, но никто не возвращается... точно как Блестяшка.' WHERE `entry` = 2000005006;
UPDATE `dbscript_string` SET `content_loc8`='Спроси Киблера о сокровище! ЩЕЛК!' WHERE `entry` = 2000005007;
UPDATE `dbscript_string` SET `content_loc8`='ЩЕЛК! *кх* *кх* Нужно бросать курить!' WHERE `entry` = 2000005008;
UPDATE `dbscript_string` SET `content_loc8`='Молодец, солдат! Вольно!' WHERE `entry` = 2000005009;
UPDATE `dbscript_string` SET `content_loc8`='Заг-заг! Рад был помочь!' WHERE `entry` = 2000005010;
UPDATE `dbscript_string` SET `content_loc8`='Да, прямо сейчас мама!' WHERE `entry` = 2000005011;
UPDATE `dbscript_string` SET `content_loc8`='Ох, должно быть это он... нет?' WHERE `entry` = 2000005018;
UPDATE `dbscript_string` SET `content_loc8`='Крепость Короля-лича строится. Крайне важно, что бы все шло по его плану.' WHERE `entry` = 2000005027;
UPDATE `dbscript_string` SET `content_loc8`='Завтра мы начнем подготовку наших лучших драконов, поэтому не забудьте свои жевательные игрушки.' WHERE `entry` = 2000005028;
UPDATE `dbscript_string` SET `content_loc8`='Когти наших драконов все еще далеки от зрелости, но с терпением и исследованиями, мы уверены, что драконы в скором времени будут готовы.' WHERE `entry` = 2000005029;
UPDATE `dbscript_string` SET `content_loc8`='Я прибыл из дальних земель... где гибель, чума и несчастье.' WHERE `entry` = 2000005031;
UPDATE `dbscript_string` SET `content_loc8`='И тогда таурен сказал: \"13 ДЮЙМОВ!\"' WHERE `entry` = 2000005032;
UPDATE `dbscript_string` SET `content_loc8`='Он уходит!' WHERE `entry` = 2000005035;
UPDATE `dbscript_string` SET `content_loc8`='Плакса-вакса!' WHERE `entry` = 2000005057;
UPDATE `dbscript_string` SET `content_loc8`='Детка хочет куклу!' WHERE `entry` = 2000005058;
UPDATE `dbscript_string` SET `content_loc8`='Посмотрим, умеет ли твоя кукла плавать!' WHERE `entry` = 2000005059;
UPDATE `dbscript_string` SET `content_loc8`='Ха-ха! Бетси у меня!' WHERE `entry` = 2000005060;
UPDATE `dbscript_string` SET `content_loc8`='У меня твоя кукла! Бе-бе-бе!' WHERE `entry` = 2000005061;
UPDATE `dbscript_string` SET `content_loc8`='Отдай мою куклу!!!' WHERE `entry` = 2000005062;
UPDATE `dbscript_string` SET `content_loc8`='Не трогай Бетси, подлец!' WHERE `entry` = 2000005063;
UPDATE `dbscript_string` SET `content_loc8`='Ты уже $Gосвободил:освободила; Друлла? Я не знаю, где его удерживают.' WHERE `entry` = 2000005078;
UPDATE `dbscript_string` SET `content_loc8`='Не трогай Бетси, подлец!' WHERE `entry` = 2000005080;
UPDATE `dbscript_string` SET `content_loc8`='Дальше иди без меня! У меня собственный путь к Мельнице Таррен.' WHERE `entry` = 2000005082;
UPDATE `dbscript_string` SET `content_loc8`='Не трогай Бетси, подлец!' WHERE `entry` = 2000005086;
UPDATE `dbscript_string` SET `content_loc8`='Ах, как хорошо быть свободным от оков! Ты уже $Gосвободил:освободила; Тог\'тара? Люди разделили нас, когда схватили.' WHERE `entry` = 2000005081;
UPDATE `dbscript_string` SET `content_loc8`='Не трогай Бетси, подлец!' WHERE `entry` = 2000005092;
UPDATE `dbscript_string` SET `content_loc8`='Я только замедлю тебя, но никакие розово-кожие людишки не смогут удержать меня от свободы!' WHERE `entry` = 2000005079;
UPDATE `dbscript_string` SET `content_loc8`='Не трогай Бетси, подлец!' WHERE `entry` = 2000005098;
UPDATE `dbscript_string` SET `content_loc8`='Ах, какая сладкая парочка! А я тут воду разношу, одна на всю округу.' WHERE `entry` = 2000005103;
UPDATE `dbscript_string` SET `content_loc8`='Где вода, Эмма? Найди воду, Эмма... Если бы не я, они бы вообще не знали, как вода выглядит.' WHERE `entry` = 2000005104;
UPDATE `dbscript_string` SET `content_loc8`='Разумеется, я разговариваю сама с собой! Другого достойного собеседника в этом городе не найти.' WHERE `entry` = 2000005105;
UPDATE `dbscript_string` SET `content_loc8`='Как будто в моем возрасте заняться больше нечем – знай ведра носи!' WHERE `entry` = 2000005106;
UPDATE `dbscript_string` SET `content_loc8`='Я по сто раз в день хожу к этому колодцу, чтобы воды набрать. Никакого уважения к возрасту, никакого!' WHERE `entry` = 2000005107;
UPDATE `dbscript_string` SET `content_loc8`='Дежавю. Мне на мгновение показалось, что я дома... и чумы еще нет...' WHERE `entry` = 2000005108;
UPDATE `dbscript_string` SET `content_loc8`='Говорят, иногда он превращается в ворона.' WHERE `entry` = 2000005109;
UPDATE `dbscript_string` SET `content_loc8`='Говорят, иногда он превращается в ворона.' WHERE `entry` = 2000005110;
UPDATE `dbscript_string` SET `content_loc8`='И тогда кролик просто откусил ему голову... клянусь.' WHERE `entry` = 2000005111;
UPDATE `dbscript_string` SET `content_loc8`='Клянусь, народ их правда видел! Пандарены существуют!' WHERE `entry` = 2000005112;
UPDATE `dbscript_string` SET `content_loc8`='Знаешь, почему у орков глаза красным светятся? Это потому, что они кровь пьют!' WHERE `entry` = 2000005113;
UPDATE `dbscript_string` SET `content_loc8`='Вряд ли в этих каналах вообще водится рыба.' WHERE `entry` = 2000005114;
UPDATE `dbscript_string` SET `content_loc8`='Вот так Лотар и убил тридцать шесть орков голыми руками!' WHERE `entry` = 2000005115;
UPDATE `dbscript_string` SET `content_loc8`='Фу-у... Это не рыба!' WHERE `entry` = 2000005116;
UPDATE `dbscript_string` SET `content_loc8`='Мои ботинки все в червячьих потрохах.' WHERE `entry` = 2000005117;
UPDATE `dbscript_string` SET `content_loc8`='Мне кажется, я что-то слышал.' WHERE `entry` = 2000005118;
UPDATE `dbscript_string` SET `content_loc8`='Фу-у... Это не рыба!' WHERE `entry` = 2000005119;
UPDATE `dbscript_string` SET `content_loc8`='Мне кажется, я что-то слышал.' WHERE `entry` = 2000005120;
UPDATE `dbscript_string` SET `content_loc8`='Хоть бы это была рыба!' WHERE `entry` = 2000005121;
UPDATE `dbscript_string` SET `content_loc8`='Червя на крючок, крючок в воду. А в воде рыба. Наша рыба!' WHERE `entry` = 2000005122;
UPDATE `dbscript_string` SET `content_loc8`='Можете представить?' WHERE `entry` = 2000005123;
UPDATE `dbscript_string` SET `content_loc8`='Да ну?' WHERE `entry` = 2000005124;
UPDATE `dbscript_string` SET `content_loc8`='Ух ты.' WHERE `entry` = 2000005125;
UPDATE `dbscript_string` SET `content_loc8`='А мой папа говорит, что все это выдумки.' WHERE `entry` = 2000005126;
UPDATE `dbscript_string` SET `content_loc8`='Да ну?' WHERE `entry` = 2000005127;
UPDATE `dbscript_string` SET `content_loc8`='Ух ты.' WHERE `entry` = 2000005128;
UPDATE `dbscript_string` SET `content_loc8`='Неплохо.' WHERE `entry` = 2000005129;
UPDATE `dbscript_string` SET `content_loc8`='Ух ты.' WHERE `entry` = 2000005130;
UPDATE `dbscript_string` SET `content_loc8`='Да ну?' WHERE `entry` = 2000005131;
UPDATE `dbscript_string` SET `content_loc8`='Поживее, молодцы! Нас тут работа ждет!' WHERE `entry` = 2000005132;
UPDATE `dbscript_string` SET `content_loc8`='А это Собор Света – центр духовного просвещения Штормграда.' WHERE `entry` = 2000005134;
UPDATE `dbscript_string` SET `content_loc8`='Да, это так. В стенах Храма учатся и постигают истину и жрецы, и паладины.' WHERE `entry` = 2000005135;
UPDATE `dbscript_string` SET `content_loc8`='Дети, если вы угомонитесь и пойдете за мной, мы с вами осмотрим трон, на котором восседает сам Андуин Ринн.' WHERE `entry` = 2000005136;
UPDATE `dbscript_string` SET `content_loc8`='А это – крепость Штормграда. Она построена на руинах замка, разрушенного Ордой во время первой Великой войны.' WHERE `entry` = 2000005137;
UPDATE `dbscript_string` SET `content_loc8`='Когда Орда была сокрушена, люди вернулись сюда и начали отстраивать наш великий город.' WHERE `entry` = 2000005138;
UPDATE `dbscript_string` SET `content_loc8`='Ну хорошо... пойдем на Аллею Героев, к памятнику величайшим героям двух великих войн. Не отставайте.' WHERE `entry` = 2000005139;
UPDATE `dbscript_string` SET `content_loc8`='Не правда ли, восхитительно, дети? Каждого, кто входит в город, встречают бдительные взгляды наших величайших героев.' WHERE `entry` = 2000005140;
UPDATE `dbscript_string` SET `content_loc8`='Сердце замирает... Дети, когда мы вернемся в школу, каждый из вас сделает доклад об одной из этих легендарных личностей.' WHERE `entry` = 2000005141;
UPDATE `dbscript_string` SET `content_loc8`='Посмотрите еще раз, а потом мы с вами отправимся на соборный двор и увидим великий Собор Света.' WHERE `entry` = 2000005142;
UPDATE `dbscript_string` SET `content_loc8`='Если мы изменим направление потока Сущности на противоположное, возможно, нам удастся сменить его полярность.' WHERE `entry` = 2000005148;
UPDATE `dbscript_string` SET `content_loc8`='Почему же нельзя сдвинуть решетку и уравнять изменение потока?' WHERE `entry` = 2000005149;
UPDATE `dbscript_string` SET `content_loc8`='Затем поток магии переходит в состояние цепной реакции позитивно заряженной энергии.' WHERE `entry` = 2000005150;
UPDATE `dbscript_string` SET `content_loc8`='Чтобы обереги работали, их нужно непрерывно подпитывать энергией.' WHERE `entry` = 2000005151;
UPDATE `dbscript_string` SET `content_loc8`='Магинор утверждает, что вплетение дополнительных струй положительной энергии повышает стабильность потока.' WHERE `entry` = 2000005152;
UPDATE `dbscript_string` SET `content_loc8`='Портал слегка нестабилен, но если в этот момент провести связующий ритуал, он останется на месте.' WHERE `entry` = 2000005153;
UPDATE `dbscript_string` SET `content_loc8`='Когда положительно заряженные энергии сталкиваются с негативно заряженными, они не нейтрализуют друг друга.' WHERE `entry` = 2000005154;
UPDATE `dbscript_string` SET `content_loc8`='Если добавить двенадцать точек фокуса, то магические силы, возможно, станут крепче, прибавляя необходимую устойчивость.' WHERE `entry` = 2000005155;
UPDATE `dbscript_string` SET `content_loc8`='Не стоит. Хватит с меня взрывов.' WHERE `entry` = 2000005156;
UPDATE `dbscript_string` SET `content_loc8`='Думаю, это бы сработало, если б у нас было двадцать воинов.' WHERE `entry` = 2000005157;
UPDATE `dbscript_string` SET `content_loc8`='А это разве не приводит к пересечению потоков? Это разве не плохо?' WHERE `entry` = 2000005158;
UPDATE `dbscript_string` SET `content_loc8`='А что если использовать изменение частоты для передачи магических сигналов вверх по потоку?' WHERE `entry` = 2000005159;
UPDATE `dbscript_string` SET `content_loc8`='А разве не в этом причина основных проблем с магическими формулами посвященной Силерии?' WHERE `entry` = 2000005160;
UPDATE `dbscript_string` SET `content_loc8`='Однако это нарушит баланс магической фокусировки и инвертирует астральные вибрации.' WHERE `entry` = 2000005161;
UPDATE `dbscript_string` SET `content_loc8`='А если плетение не закрепить перед началом работы, оно не распустится?' WHERE `entry` = 2000005162;
UPDATE `dbscript_string` SET `content_loc8`='Впрочем, результирующая энергия может сколлапсировать, и тогда неделя головной боли тебе обеспечена.' WHERE `entry` = 2000005163;
UPDATE `dbscript_string` SET `content_loc8`='По крайней мере, нас тут не будет, когда придется все это убирать.' WHERE `entry` = 2000005164;
UPDATE `dbscript_string` SET `content_loc8`='И все это за любовное зелье? Надеюсь, он того стоит.' WHERE `entry` = 2000005165;
UPDATE `dbscript_string` SET `content_loc8`='Только если мы нарушим процедуру инициализации.' WHERE `entry` = 2000005166;
UPDATE `dbscript_string` SET `content_loc8`='Правда, что здесь обучают паладинов?' WHERE `entry` = 2000005167;
UPDATE `dbscript_string` SET `content_loc8`='Почему мы должны изучать этот материал?' WHERE `entry` = 2000005168;
UPDATE `dbscript_string` SET `content_loc8`='А что если использовать три точки фокуса по тирейской схеме? Возможно, это хорошее решение.' WHERE `entry` = 2000005169;
UPDATE `dbscript_string` SET `content_loc8`='Вот так всегда. Шансы, что это случится, равны нулю – или еще меньше.' WHERE `entry` = 2000005170;
UPDATE `dbscript_string` SET `content_loc8`='Если обратиться к сурийской теории, то да, а если использовать изерический подход – то нет.' WHERE `entry` = 2000005171;
UPDATE `dbscript_string` SET `content_loc8`='Но если установить стабилизирующий якорь в нужном энергетическом перекрестье, все сработает.' WHERE `entry` = 2000005172;
UPDATE `dbscript_string` SET `content_loc8`='Если делать все правильно, с нами ничего не будет. Изучим все как следует, а потом начнем.' WHERE `entry` = 2000005173;
UPDATE `dbscript_string` SET `content_loc8`='Привет, Черис. Вот список. Можешь достать все это? Особенно последний ингредиент.' WHERE `entry` = 2000005180;
UPDATE `dbscript_string` SET `content_loc8`='Конечно, Пейдж. Не спеши.' WHERE `entry` = 2000005181;
UPDATE `dbscript_string` SET `content_loc8`='Спасибо Чариса. Пойдем Пейдж.' WHERE `entry` = 2000005182;
UPDATE `dbscript_string` SET `content_loc8`='Мама, а можно я возьму домой Пшикса?' WHERE `entry` = 2000005183;
UPDATE `dbscript_string` SET `content_loc8`='Билли говорит, что Пшикс когда-то был великим волшебником. Но потом он как-то не так прочел заклинание и превратился в кролика.' WHERE `entry` = 2000005184;
UPDATE `dbscript_string` SET `content_loc8`='Голова раскалывается от магии? Отдохните в \"Синем отшельнике\"!' WHERE `entry` = 2000005185;
UPDATE `dbscript_string` SET `content_loc8`='Лучшие напитки в Штормграде!' WHERE `entry` = 2000005186;
UPDATE `dbscript_string` SET `content_loc8`='В \"Синем отшельнике\" вы всегда будете чувствовать себя в своей тарелке!' WHERE `entry` = 2000005187;
UPDATE `dbscript_string` SET `content_loc8`='Вас снедает печаль? В \"Синем отшельнике\" вы найдете, с кем ее разделить!' WHERE `entry` = 2000005188;
UPDATE `dbscript_string` SET `content_loc8`='Лучшие напитки в Штормграде!' WHERE `entry` = 2000005189;
UPDATE `dbscript_string` SET `content_loc8`='Голова раскалывается от магии? Отдохните в \"Синем отшельнике\"!' WHERE `entry` = 2000005190;
UPDATE `dbscript_string` SET `content_loc8`='Хочешь получить бесплатную выпивку в \"Синем отшельнике\"? Спроси меня как!' WHERE `entry` = 2000005191;
UPDATE `dbscript_string` SET `content_loc8`='В \"Синем отшельнике\" вы всегда будете чувствовать себя в своей тарелке!' WHERE `entry` = 2000005192;
UPDATE `dbscript_string` SET `content_loc8`='Бесплатные напитки в \"Синем Отшельнике\"!' WHERE `entry` = 2000005193;
UPDATE `dbscript_string` SET `content_loc8`='Вас снедает печаль? В \"Синем отшельнике\" вы найдете, с кем ее разделить!' WHERE `entry` = 2000005194;
UPDATE `dbscript_string` SET `content_loc8`='Голова раскалывается от магии? Отдохните в \"Синем отшельнике\"!' WHERE `entry` = 2000005195;
UPDATE `dbscript_string` SET `content_loc8`='Лучшие напитки в Штормграде!' WHERE `entry` = 2000005196;
UPDATE `dbscript_string` SET `content_loc8`='Хочешь получить бесплатную выпивку в \"Синем отшельнике\"? Спроси меня как!' WHERE `entry` = 2000005197;
UPDATE `dbscript_string` SET `content_loc8`='В \"Синем отшельнике\" вы всегда будете чувствовать себя в своей тарелке!' WHERE `entry` = 2000005198;
UPDATE `dbscript_string` SET `content_loc8`='Лучшие напитки в Штормграде!' WHERE `entry` = 2000005199;
UPDATE `dbscript_string` SET `content_loc8`='Что это был за шум? Похоже на рев!' WHERE `entry` = 2000005200;
UPDATE `dbscript_string` SET `content_loc8`='%s издает рев, чтобы привлечь внимание Терентис.' WHERE `entry` = 2000005201;
UPDATE `dbscript_string` SET `content_loc8`='Лютый Коготь? Полегче, друг мой... где твой хозяин Волкор?' WHERE `entry` = 2000005202;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает стонать и реветь на Терентис, топча лапами о землю.' WHERE `entry` = 2000005203;
UPDATE `dbscript_string` SET `content_loc8`='Подожди, подожди друг мой. Секундочку...' WHERE `entry` = 2000005204;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает применять заклинание на Лютого Когтя.' WHERE `entry` = 2000005205;
UPDATE `dbscript_string` SET `content_loc8`='Вот... это должно помочь. А теперь, Лютый Коготь, расскажи, что же случило?' WHERE `entry` = 2000005206;
UPDATE `dbscript_string` SET `content_loc8`='%s еще сильнее ревет на Терентис, похоже, что на этот раз, друид понимает медведя.' WHERE `entry` = 2000005207;
UPDATE `dbscript_string` SET `content_loc8`='Я понимаю, друг мой. Я попытаюсь найти кого-нибудь, кто мог бы помочь твоему хозяину. Иди к нему и оставайся рядом.' WHERE `entry` = 2000005208;
UPDATE `dbscript_string` SET `content_loc8`='%s признательно ревет на Терентис.' WHERE `entry` = 2000005209;
UPDATE `dbscript_string` SET `content_loc8`='Если у вас есть время, Лютый Коготь и его хозяин Волкор, могли бы использовать вашу помощь. Если вы заинтересованы, поговорите со мной еще...' WHERE `entry` = 2000005210;
UPDATE `dbscript_string` SET `content_loc8`='Привет! Соус нравится? Правда, вкусный?' WHERE `entry` = 2000005214;
UPDATE `dbscript_string` SET `content_loc8`='Из-чего-литель? А, Испепелитель? Впервые слышу... Чего? Да отстань уже!' WHERE `entry` = 2000005215;
UPDATE `dbscript_string` SET `content_loc8`='Эй, кто-нибудь, помогите мне поймать эту штуку!' WHERE `entry` = 2000005218;
UPDATE `dbscript_string` SET `content_loc8`='Надо было выпить пилюльку невидимости...' WHERE `entry` = 2000005228;
UPDATE `dbscript_string` SET `content_loc8`='За эту работу мне слишком мало платят!' WHERE `entry` = 2000005229;
UPDATE `dbscript_string` SET `content_loc8`='Присядь сюда, и ты услышишь та... *ик!* та... *ик!* таййй... *ик!!!* Чтоб тебя!' WHERE `entry` = 2000005233;
UPDATE `dbscript_string` SET `content_loc8`='Демоны заберите эти налоги! Какое тут \"спи спокойно\"?!' WHERE `entry` = 2000005234;
UPDATE `dbscript_string` SET `content_loc8`='Время моего патруля. Я скоро вернусь.' WHERE `entry` = 2000005235;
UPDATE `dbscript_string` SET `content_loc8`='Жители Оргриммара и союзники Орды, соберитесь вокруг своего героя, героя Орды. В этот день, $N, под знаменем нашего вождя, $gпрошелся:прошлась; смертельным ударом по черным драконам. Праматерь Ониксия, пала!' WHERE `entry` = 2000005236;
UPDATE `dbscript_string` SET `content_loc8`='В доказательство неоспоримой мощи нашего вождя! Был поднят боевой клич победителя драконов!' WHERE `entry` = 2000005237;
UPDATE `dbscript_string` SET `content_loc8`='Граждане Альянса! В этот день вершиться история. $N $gположил:положила; конец тому, кто хотел захватить власть всего королевства! Соберитесь вокруг своего защитника, грейтесь в лучах его славы!' WHERE `entry` = 2000005238;
UPDATE `dbscript_string` SET `content_loc8`='Узрите мощь всего Альянса! Голова ужасной леди Ониксии свисает с арки! Воспряньте же духом и радостно восславьте победителя драконов!' WHERE `entry` = 2000005239;
UPDATE `dbscript_string` SET `content_loc8`='Довольно простая задача разбить этот самоцвет душ!' WHERE `entry` = 2000005240;
UPDATE `dbscript_string` SET `content_loc8`='Светящийся самоцвет души разрывается!' WHERE `entry` = 2000005241;
UPDATE `dbscript_string` SET `content_loc8`='Во время разлома, в Амет\'Аране бушевал кошмар, которым были охвачены все земли. Было мало надежды на спасение.' WHERE `entry` = 2000005242;
UPDATE `dbscript_string` SET `content_loc8`='Атрикус пришел к нам. Он сказал, что может спасти нас от вреда. Он наложил на нас заклинание защиты от урона.' WHERE `entry` = 2000005243;
UPDATE `dbscript_string` SET `content_loc8`='Когда тряска остановилась, стали ясны его мотивы. Но мы оказались в ловушке, и он медленно вытащил из нас нашу силу.' WHERE `entry` = 2000005244;
UPDATE `dbscript_string` SET `content_loc8`='Были сотни заключенных в его заклинаниях. Сейчас лишь немногие остались там. Иногда он говорит с нами.' WHERE `entry` = 2000005245;
UPDATE `dbscript_string` SET `content_loc8`='Он обеспокоен тем, что его власть ослабла. Последний из его светящихся самоцветов души увянет и умрет.' WHERE `entry` = 2000005246;
UPDATE `dbscript_string` SET `content_loc8`='Тогда мы должны положить конец Атрикусу Нарассину. Скажи мне, дух, где мы можем найти другие самоцветы душ, чтобы рассеять его магию?' WHERE `entry` = 2000005247;
UPDATE `dbscript_string` SET `content_loc8`='Его лейтенант Илкруд Магтрулл обладает томом, который может подсказать о местонахождении остальных самоцветов душ.' WHERE `entry` = 2000005248;
UPDATE `dbscript_string` SET `content_loc8`='%s исчезает в тумане...' WHERE `entry` = 2000005249;
UPDATE `dbscript_string` SET `content_loc8`='Каменная плотина спасена! Троекратное ура, $N!' WHERE `entry` = 2000005300;
UPDATE `dbscript_string` SET `content_loc8`='Босс хочет, чтобы все были в состоянии повышенной готовности. Ржавый якорь опускается сегодня ночью.' WHERE `entry` = 2000005301;
UPDATE `dbscript_string` SET `content_loc8`='Каменщики... ошибка... предупреждение для братства: ржавый якорь опускается сегодня ночью.' WHERE `entry` = 2000005302;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает водить камнем Релу над двумя окаменелостями.' WHERE `entry` = 2000005303;
UPDATE `dbscript_string` SET `content_loc8`='Клянусь звездами! Дух призван!' WHERE `entry` = 2000005304;
UPDATE `dbscript_string` SET `content_loc8`='Кто призвал Амана?' WHERE `entry` = 2000005305;
UPDATE `dbscript_string` SET `content_loc8`='А, вижу, вы старательно работаете с древностями.' WHERE `entry` = 2000005306;
UPDATE `dbscript_string` SET `content_loc8`='Помните, что даже ваши создатели небезупречны.' WHERE `entry` = 2000005307;
UPDATE `dbscript_string` SET `content_loc8`='Если слишком глубоко закопаться в прошлое, можно повредить своему будущему.' WHERE `entry` = 2000005308;
UPDATE `dbscript_string` SET `content_loc8`='%s исчезает.' WHERE `entry` = 2000005309;
UPDATE `dbscript_string` SET `content_loc8`='Это воистину тайна прошлого! Но и ключ к нашему будущему!' WHERE `entry` = 2000005310;
UPDATE `dbscript_string` SET `content_loc8`='Портер \"Черный Коготь\", это настоящая сила!' WHERE `entry` = 2000005311;
UPDATE `dbscript_string` SET `content_loc8`='У меня... кружится голова. Здесь... так... жарко...' WHERE `entry` = 2000005312;
UPDATE `dbscript_string` SET `content_loc8`='Что вообще такое эта аллергия? И какое отношение она имеет к моим кошкам?' WHERE `entry` = 2000005314;
UPDATE `dbscript_string` SET `content_loc8`='Не могу поверить, что отец не позволит мне оставить твою сестру.' WHERE `entry` = 2000005315;
UPDATE `dbscript_string` SET `content_loc8`='Не волнуйся! Я найду для тебя подходящее жилье.' WHERE `entry` = 2000005316;
UPDATE `dbscript_string` SET `content_loc8`='Кто может приютить моего прелестного маленького котенка?' WHERE `entry` = 2000005317;
UPDATE `dbscript_string` SET `content_loc8`='Кто-нибудь, пожалуйста, приютите маленького котенка!' WHERE `entry` = 2000005318;
UPDATE `dbscript_string` SET `content_loc8`='Продадим котенка в добрые руки.' WHERE `entry` = 2000005319;
UPDATE `dbscript_string` SET `content_loc8`='Папа, а можно мне взять еще камушков на ожерелье?' WHERE `entry` = 2000005320;
UPDATE `dbscript_string` SET `content_loc8`='Да, можно, Окла. Но не уходи от дома слишком далеко.' WHERE `entry` = 2000005321;
UPDATE `dbscript_string` SET `content_loc8`='Дабу! Я буду осторожна, пап!' WHERE `entry` = 2000005322;
UPDATE `dbscript_string` SET `content_loc8`='Ох... Какой красивый, яркий камень! Интересно, нет ли тут еще такого...' WHERE `entry` = 2000005323;
UPDATE `dbscript_string` SET `content_loc8`='Хмм... хороший камешек, только мелкий очень.' WHERE `entry` = 2000005324;
UPDATE `dbscript_string` SET `content_loc8`='Какой блестящий камушек, положу-ка я его себе... Ну, теперь мне надо еще несколько...' WHERE `entry` = 2000005325;
UPDATE `dbscript_string` SET `content_loc8`='Этот камень наверняка подойдет для копья, которое делает мой приятель Грук! Он очень острый... Надеюсь, ему понравится.' WHERE `entry` = 2000005326;
UPDATE `dbscript_string` SET `content_loc8`='Вот... Этих камней должно быть достаточно для создания ожерелья. Все равно мне уже пора домой.' WHERE `entry` = 2000005327;
UPDATE `dbscript_string` SET `content_loc8`='Анайя?.. Или мои глаза обманывают меня? Неужели это и вправду ты?' WHERE `entry` = 2000005336;
UPDATE `dbscript_string` SET `content_loc8`='Время не пощадило ни тебя, ни меня, любовь моя, но это неважно. Главное, что мы наконец вместе.' WHERE `entry` = 2000005337;
UPDATE `dbscript_string` SET `content_loc8`='Что судьба в жестокости своей позволит нам лишь это после тысячи лет разлуки...' WHERE `entry` = 2000005338;
UPDATE `dbscript_string` SET `content_loc8`='Ты меня ненавидишь, любовь моя? Мне пришлось разрушить твою оболочку, чтобы освободить дух от бренного тела.' WHERE `entry` = 2000005339;
UPDATE `dbscript_string` SET `content_loc8`='Пусть это не тревожит тебя, любимый. Ты освободил меня от рабства, и за это я тебя еще больше люблю.' WHERE `entry` = 2000005340;
UPDATE `dbscript_string` SET `content_loc8`='Увы, и это придется прервать... Узы, что связывают меня с этим миром, слабеют... Меня уносит прочь...' WHERE `entry` = 2000005341;
UPDATE `dbscript_string` SET `content_loc8`='Нет! Анайя... Анайя! Не оставляй меня! Прошу тебя...' WHERE `entry` = 2000005342;
UPDATE `dbscript_string` SET `content_loc8`='Прощай, Кириллиан, до встречи в лучшем мире...' WHERE `entry` = 2000005343;
UPDATE `dbscript_string` SET `content_loc8`='%s говорит, и ее мягкий голос растворяется в тумане: \"Всегда помни, что я люблю тебя!\"' WHERE `entry` = 2000005344;
UPDATE `dbscript_string` SET `content_loc8`='Как же, любовь моя? Где взять силы прожить вечность без тебя?..' WHERE `entry` = 2000005345;
UPDATE `dbscript_string` SET `content_loc8`='Никто не похитит тайны Создателей.' WHERE `entry` = 2000005346;
UPDATE `dbscript_string` SET `content_loc8`='%s очищает от пыли основание артефакта.' WHERE `entry` = 2000005347;
UPDATE `dbscript_string` SET `content_loc8`='%s тщательно изучает большую вазу.' WHERE `entry` = 2000005348;
UPDATE `dbscript_string` SET `content_loc8`='Бедный Дориус. Если мне когда-нибудь в руки попадется черное железо, поможешь мне...' WHERE `entry` = 2000005349;
UPDATE `dbscript_string` SET `content_loc8`='Если тебе нужен ключ, поймай меня!' WHERE `entry` = 2000005460;
UPDATE `dbscript_string` SET `content_loc8`='Догони меня, попробуй! Я бегу и не боюсь!' WHERE `entry` = 2000005461;
UPDATE `dbscript_string` SET `content_loc8`='С чего бы ты станешь мне вредить?! Пойдем. Мы ведь можем подружиться!' WHERE `entry` = 2000005462;
UPDATE `dbscript_string` SET `content_loc8`='Умереть?! Пузиллин будет плакать!' WHERE `entry` = 2000005463;
UPDATE `dbscript_string` SET `content_loc8`='Поздоровайся с моими маленькими друзьями!' WHERE `entry` = 2000005464;
UPDATE `dbscript_string` SET `content_loc8`='$N, посмотрите на образец гнусь-лозы, которую, мне удалось принести с собой из пещеры, для того, чтобы вы знали что искать...' WHERE `entry` = 2000005465;
UPDATE `dbscript_string` SET `content_loc8`='О нет! Вот и они!' WHERE `entry` = 2000005547;
UPDATE `dbscript_string` SET `content_loc8`='Я уношу отсюда ноги!' WHERE `entry` = 2000005548;
UPDATE `dbscript_string` SET `content_loc8`='Что? Да как ты смеешь говорить мне такое?' WHERE `entry` = 2000005549;
UPDATE `dbscript_string` SET `content_loc8`='После всего, через что мы прошли? Ну и ладно, ты мне все равно не $gнравился:нравилась;!' WHERE `entry` = 2000005550;
UPDATE `dbscript_string` SET `content_loc8`='Я уношу отсюда ноги!' WHERE `entry` = 2000005551;
UPDATE `dbscript_string` SET `content_loc8`='Кто посмел вторгнуться в мои владения?!' WHERE `entry` = 2000005552;
UPDATE `dbscript_string` SET `content_loc8`='Выдвигаемся!' WHERE `entry` = 2000005553;
UPDATE `dbscript_string` SET `content_loc8`='Обыскать этот завал!' WHERE `entry` = 2000005554;
UPDATE `dbscript_string` SET `content_loc8`='Найдите мне что-то стоящее, собаки!' WHERE `entry` = 2000005555;
UPDATE `dbscript_string` SET `content_loc8`='Подожди... ты $gслышал:слышала; это? Что-то приближается с запада!' WHERE `entry` = 2000005627;
UPDATE `dbscript_string` SET `content_loc8`='Я бежала уворачиваясь от стрел! Я боюсь, что, если они придут, тебе придется заняться ими в одиночку, друг мой.' WHERE `entry` = 2000005628;
UPDATE `dbscript_string` SET `content_loc8`='Хвала Элуне! Я даже не знаю, удалось ли бы мне выжить в этот день без твоей помощи.' WHERE `entry` = 2000005629;
UPDATE `dbscript_string` SET `content_loc8`='Кажется, лекарство действует. Нога уже не так болит... А теперь извини, мне надо доложить начальству о случившемся.' WHERE `entry` = 2000005630;
UPDATE `dbscript_string` SET `content_loc8`='Пожалуйста, поговори с Часовой Ойнеей на заставе Мейстры в Ясеневом лесу: она позаботится о том, чтобы тебя достойно наградили за проявленное сегодня мужество.' WHERE `entry` = 2000005631;
UPDATE `dbscript_string` SET `content_loc8`='Всем приготовиться! Наги наступают!' WHERE `entry` = 2000005632;
UPDATE `dbscript_string` SET `content_loc8`='Если мы сможем сдержать их, я уверен, что мы будем вне опасности.' WHERE `entry` = 2000005633;
UPDATE `dbscript_string` SET `content_loc8`='Ну, раз уж вы здесь, я научу вас призывать демонические воинства, покорные вашей воле. Начнем с самых простых существ такого рода. Итак, приступим.' WHERE `entry` = 2000005634;
UPDATE `dbscript_string` SET `content_loc8`='Из всех демонических созданий проще всего призвать беса. Думаю, вы уже знакомы с этим существом, но для полноты картины я все-таки расскажу вам о нем.' WHERE `entry` = 2000005635;
UPDATE `dbscript_string` SET `content_loc8`='Это мерзкое маленькое существо зовется бесом. Он очень маленький и в качестве живой стены не подойдет, да и урон наносит весьма слабый. Если он для чего и годится, то только для поддержки большой группы.' WHERE `entry` = 2000005636;
UPDATE `dbscript_string` SET `content_loc8`='Теперь, после того как вы получили возможность изучить беса, перейдем к следующему существу которого вы можете призвать, демону Бездны.' WHERE `entry` = 2000005637;
UPDATE `dbscript_string` SET `content_loc8`='Эта демоническая сущность известная как демон Бездны. Его показатели силы и выносливость высоки, что делает его отличным защитником. Натравите его на врага, а потом спрячьтесь за ним, как за щитом, чтобы безопасно применять заклинания и вытягивать из противников жизненные силы.' WHERE `entry` = 2000005638;
UPDATE `dbscript_string` SET `content_loc8`='Те, кто ни разу не видел этого создания, многое потеряли. Оно эффективно как на поле боя, так и вне его. А теперь рассмотрим существо, которого с нетерпением ждут все ученики мужского пола. Итак, суккуб.' WHERE `entry` = 2000005639;
UPDATE `dbscript_string` SET `content_loc8`='Итак, начнем. Это прекрасное создание будет не только отвлекать внимание ваших врагов – особенно мужчин, – но и наносить им вполне ощутимый урон. К сожалению, в роли живого щита оно практически бесполезно из-за слабого здоровья.' WHERE `entry` = 2000005640;
UPDATE `dbscript_string` SET `content_loc8`='Учитесь хорошо, и в один прекрасный день вы сможете призвать себе такого же питомца. А пока что займемся охотником Скверны.' WHERE `entry` = 2000005641;
UPDATE `dbscript_string` SET `content_loc8`='Существо, которое вы видите перед собой, называется охотником Скверны. Оно обладает множеством врожденных способностей, среди которых следует особо отметить Запрет чар. По этой причине такие питомцы особенно эффективны в бою с противниками, использующими магию.' WHERE `entry` = 2000005642;
UPDATE `dbscript_string` SET `content_loc8`='Если вы встретитесь с каким-нибудь заклинателем, этот зверь вам очень пригодится. А теперь посмотрим на кое-кого еще. Вот это животное поможет вам в путешествиях и значительно облегчит жизнь в дальних походах. Перед вами конь Скверны.' WHERE `entry` = 2000005643;
UPDATE `dbscript_string` SET `content_loc8`='Думаю, вам не часто доводилось видеть подобных существ. Эти демонические представители семейства лошадиных позволяют перемещаться с огромной скоростью – если держать их под контролем. А это не так-то просто. Если вы не уверены в своих силах, лучше не пробуйте.' WHERE `entry` = 2000005644;
UPDATE `dbscript_string` SET `content_loc8`='Вот так. Урок призывания окончен. Скоро начнется новый, так что, если вы хотите повторить, можете, не стесняясь, оставаться.' WHERE `entry` = 2000005645;
UPDATE `dbscript_string` SET `content_loc8`='Желаешь узнать о камне? Следуй за мной.' WHERE `entry` = 2000005646;
UPDATE `dbscript_string` SET `content_loc8`='Я очень долго блуждал в своей проклятой форме. Ты $gосвободил:освободила; меня... Твой труд должен быть вознагражден.' WHERE `entry` = 2000005647;
UPDATE `dbscript_string` SET `content_loc8`='Пожалуйста, делай все так, как я говорю тебе, $N.' WHERE `entry` = 2000005648;
UPDATE `dbscript_string` SET `content_loc8`='Прочти этот том, который я положил перед тобой, и произнеси эти слова вслух.' WHERE `entry` = 2000005649;
UPDATE `dbscript_string` SET `content_loc8`='%s направляет свою энергию, фокусируя ее на камне.' WHERE `entry` = 2000005650;
UPDATE `dbscript_string` SET `content_loc8`='Две части, соединенные вместе, снова станут единым целым.' WHERE `entry` = 2000005651;
UPDATE `dbscript_string` SET `content_loc8`='Шал миринан ишну далдора...' WHERE `entry` = 2000005652;
UPDATE `dbscript_string` SET `content_loc8`='Мой скипетр снова станет единым целым!' WHERE `entry` = 2000005653;
UPDATE `dbscript_string` SET `content_loc8`='%s берет цель орка...' WHERE `entry` = 2000005730;
UPDATE `dbscript_string` SET `content_loc8`='%s промахивается...' WHERE `entry` = 2000005731;
UPDATE `dbscript_string` SET `content_loc8`='%s прицеливается более тщательно...' WHERE `entry` = 2000005732;
UPDATE `dbscript_string` SET `content_loc8`='%s снова промахивается...' WHERE `entry` = 2000005733;
UPDATE `dbscript_string` SET `content_loc8`='%s случайно наводит прицел на цель орка...' WHERE `entry` = 2000005734;
UPDATE `dbscript_string` SET `content_loc8`='%s попадает!' WHERE `entry` = 2000005735;
UPDATE `dbscript_string` SET `content_loc8`='%s прицеливается на бутылки...' WHERE `entry` = 2000005736;
UPDATE `dbscript_string` SET `content_loc8`='%s промахивается...' WHERE `entry` = 2000005737;
UPDATE `dbscript_string` SET `content_loc8`='%s снова прицеливается на бутылки...' WHERE `entry` = 2000005738;
UPDATE `dbscript_string` SET `content_loc8`='%s снова промахивается...' WHERE `entry` = 2000005739;
UPDATE `dbscript_string` SET `content_loc8`='%s начинается быстро стрелять в центр мишени...' WHERE `entry` = 2000005740;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает целится в бутылки...' WHERE `entry` = 2000005741;
UPDATE `dbscript_string` SET `content_loc8`='%s попадает только в бок ящика!' WHERE `entry` = 2000005742;
UPDATE `dbscript_string` SET `content_loc8`='%s быстро стреляет в манекен орка...' WHERE `entry` = 2000005743;
UPDATE `dbscript_string` SET `content_loc8`='%s поворачивается к мишени...' WHERE `entry` = 2000005744;
UPDATE `dbscript_string` SET `content_loc8`='%s стреляет от бедра по бутылкам...' WHERE `entry` = 2000005745;
UPDATE `dbscript_string` SET `content_loc8`='Итак, давай попробуем...' WHERE `entry` = 2000005752;
UPDATE `dbscript_string` SET `content_loc8`='Ох, это ужасно!' WHERE `entry` = 2000005753;
UPDATE `dbscript_string` SET `content_loc8`='Я буду тренироваться и стану воином, как мой отец!' WHERE `entry` = 2000005767;
UPDATE `dbscript_string` SET `content_loc8`='А теперь поищем доверчивую гарпию!' WHERE `entry` = 2000005768;
UPDATE `dbscript_string` SET `content_loc8`='Получай! За Орду!' WHERE `entry` = 2000005769;
UPDATE `dbscript_string` SET `content_loc8`='Хватайте эту паршивую гарпию! Ага-а-а!' WHERE `entry` = 2000005770;
UPDATE `dbscript_string` SET `content_loc8`='Тебе не уйти от воина Орды! Взять! И это тоже!' WHERE `entry` = 2000005771;
UPDATE `dbscript_string` SET `content_loc8`='А теперь возвращайся обратно!' WHERE `entry` = 2000005772;
UPDATE `dbscript_string` SET `content_loc8`='А-а-а... Еще одна славная победа Орды!' WHERE `entry` = 2000005773;
UPDATE `dbscript_string` SET `content_loc8`='Заходи, Могг. Пока твоего отца нет дома, здесь небезопасно.' WHERE `entry` = 2000005774;
UPDATE `dbscript_string` SET `content_loc8`='А когда мой папа вернется из ущелья Песни Войны? Его уже так долго нету...' WHERE `entry` = 2000005775;
UPDATE `dbscript_string` SET `content_loc8`='$N, я прослежу за тем, чтобы все мои друзья из Картеля узнали, что вы спасли мне жизнь. Вот, мне необходимо избавиться от некоторых вещей, чтобы мой путь был легким, пожалуйста, посмотрите, может, чего найдете для себя полезного. Еще раз спасибо! До встречи!' WHERE `entry` = 2000005776;
UPDATE `dbscript_string` SET `content_loc8`='%s выслушивает доклад...' WHERE `entry` = 2000005777;
UPDATE `dbscript_string` SET `content_loc8`='Что? Пылающий Клинок распространяет свое влияние? Мы должны это расследовать!' WHERE `entry` = 2000005778;
UPDATE `dbscript_string` SET `content_loc8`='%s разбивает клешню.' WHERE `entry` = 2000005779;
UPDATE `dbscript_string` SET `content_loc8`='Арр, бей-круши! А у меня есть лишние сокровища – прямо на арене Гурубаши! Чтобы их взять, тебе надо открыть сундук, который я оставил на ринге арены!' WHERE `entry` = 2000005783;
UPDATE `dbscript_string` SET `content_loc8`='Пускай кровь льется рекой!' WHERE `entry` = 2000005784;
UPDATE `dbscript_string` SET `content_loc8`='Нам нужно поторопиться.' WHERE `entry` = 2000005780;
UPDATE `dbscript_string` SET `content_loc8`='Духи леса появляются и внемлют зову природы!' WHERE `entry` = 2000005781;
UPDATE `dbscript_string` SET `content_loc8`='Духи леса, вы нужны! Поспешите в Обугленную долину!' WHERE `entry` = 2000005782;
UPDATE `dbscript_string` SET `content_loc8`='Вы погибните здесь. *Ваш разум заполняется видениями хаоса и разрушения.*' WHERE `entry` = 2000000353;
UPDATE `dbscript_string` SET `content_loc8`='Покинь это место. *Реликвия испускает белую, горячую дугу пламени. Воспоминания пробудились: одинокий дворф черного железа, окруженный семью телами, стоит на коленях перед монолитом пламени.*' WHERE `entry` = 2000000354;
UPDATE `dbscript_string` SET `content_loc8`='$gОсквернитель:Осквернительница;... ты будешь $gнаказан:наказана; за это вторжение. *Мощный поток пламени исходит от реликвии, прежде чем оно осыпалось на землю.*' WHERE `entry` = 2000000355;
UPDATE `dbscript_string` SET `content_loc8`='Помоги нам. *Реликвия рассыпается в пыль. Видение восьмерых дворфов черного железа, исполняющих какой-то ритуал, заполняются вашу голову.*' WHERE `entry` = 2000000356;
UPDATE `dbscript_string` SET `content_loc8`='Твое существование будет признано. *Реликвия превращается в пыль. С приобретением мудрости, ваша голова начинает раскаливаться. Что-то ужасное скрывается в самом сердце горы.*' WHERE `entry` = 2000000357;
UPDATE `dbscript_string` SET `content_loc8`='Покинь это место. *Реликвия испускает белую, горячую дугу пламени. Воспоминания пробудились: одинокий дворф черного железа, окруженный семью телами, стоит на коленях перед монолитом пламени.*' WHERE `entry` = 2000000358;
UPDATE `dbscript_string` SET `content_loc8`='Его невозможно победить. *Реликвия сгорает, ничего не оставляя после себя. Этот город был разрушен существом, не от мира сего.*' WHERE `entry` = 2000000359;
UPDATE `dbscript_string` SET `content_loc8`='Не оскверняй эти руины, смертное существо. *Вы охвачены ослепительной вспышкой света. Единственное что вы помните, так это существо, полностью состоящее из пламени.*' WHERE `entry` = 2000000360;
UPDATE `dbscript_string` SET `content_loc8`='Вытащи его оттуда!' WHERE `entry` = 2000005099;
UPDATE `dbscript_string` SET `content_loc8`='Ограбиси сделает маленькую шляпку из твоей головы!' WHERE `entry` = 2000005100;
UPDATE `dbscript_string` SET `content_loc8`='Там, откуда я родом, дают хорошего пинка за открывание камеры заключенного!' WHERE `entry` = 2000005101;
UPDATE `dbscript_string` SET `content_loc8`='Ограбиси нужна новая шляпка.' WHERE `entry` = 2000005102;
UPDATE `dbscript_string` SET `content_loc8`='Нет! Убирайся прочь от меня! Помогите!' WHERE `entry` = 2000005626;
UPDATE `dbscript_string` SET `content_loc8`='Мне необходимо сфокусировать свою энергию на этот нож. Таким образом, я смогу уловить некоторые связанные с ним сильные духовные впечатления.' WHERE `entry` = 2000000521;
UPDATE `dbscript_string` SET `content_loc8`='Я... кажется, я увидел достаточно... так истощен.' WHERE `entry` = 2000000522;
UPDATE `dbscript_string` SET `content_loc8`='История... хм... позвольте мне ознакомиться с ней.' WHERE `entry` = 2000000523;
UPDATE `dbscript_string` SET `content_loc8`='%s бегло просматривает страницы книги.' WHERE `entry` = 2000000524;
UPDATE `dbscript_string` SET `content_loc8`='Невероятно! Кажется, я нашел то что искал, $N.' WHERE `entry` = 2000000525;
UPDATE `dbscript_string` SET `content_loc8`='Превосходно, Малтрейк. Похоже, мой план сработал. Что скажешь, смертное существо?' WHERE `entry` = 2000000526;
UPDATE `dbscript_string` SET `content_loc8`='%s издает рептилий смех... по крайней мере, вам так кажется, что это смех.' WHERE `entry` = 2000000527;
UPDATE `dbscript_string` SET `content_loc8`='Но ты же не $gпомог:помогла; бы легиону Черной горы, если бы тебя просто попросили, не так ли?' WHERE `entry` = 2000000528;
UPDATE `dbscript_string` SET `content_loc8`='Что мы будем делать с $gним:ней;, хозяин? Теперь $gон бесполезен:она бесполезна; для нас.' WHERE `entry` = 2000000529;
UPDATE `dbscript_string` SET `content_loc8`='ЗАМОЛКНИ, ГЛУПЕЦ!' WHERE `entry` = 2000000530;
UPDATE `dbscript_string` SET `content_loc8`='$gОн:Она; останется жить только потому, чтобы увидеть плоды своей работы: разрушение и хаос, которые несомненно наступят как только легион Черной горы вторгнется в ущелье.' WHERE `entry` = 2000000531;
UPDATE `dbscript_string` SET `content_loc8`='А теперь я покину тебя, $gсмертный:смертная;.$gЖивым:Живой; и с этими безделушками. Малтрейк! Предоставь $gему:ей; эти безделушки!' WHERE `entry` = 2000000532;
UPDATE `dbscript_string` SET `content_loc8`='Как прикажете, хозяин.' WHERE `entry` = 2000000533;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает быстрее взмахивать своими массивными крыльями. Похоже, он готовится к полету.' WHERE `entry` = 2000000534;
UPDATE `dbscript_string` SET `content_loc8`='Ах, да, кожа...  не потеряй ее. Мои родственники, что в Пылающих степях с радостью сделают для тебя укрепление из кожи черного дракона.' WHERE `entry` = 2000000535;
UPDATE `dbscript_string` SET `content_loc8`='Легион Черной горы идет, дворфы! Мы спалим эту землю и подожжем небеса. Никто не выживет...' WHERE `entry` = 2000000536;
UPDATE `dbscript_string` SET `content_loc8`='И так, давай посмотрим... если я не ошибаюсь, то... хм...' WHERE `entry` = 2000000540;
UPDATE `dbscript_string` SET `content_loc8`='Синий плюс красный... предсказываю...' WHERE `entry` = 2000000541;
UPDATE `dbscript_string` SET `content_loc8`='$N, вот оно! Наконец-то я понял!' WHERE `entry` = 2000000542;
UPDATE `dbscript_string` SET `content_loc8`='Вау! Неплохо! Лучшая сделка, чем я бы смог придумать сам!' WHERE `entry` = 2000000602;
UPDATE `dbscript_string` SET `content_loc8`='Эй, Нагмара! Как насчет кружечки эдя Черного Железа?' WHERE `entry` = 2000000261;
UPDATE `dbscript_string` SET `content_loc8`='Нагмара! Осталась ли еще баранина?' WHERE `entry` = 2000000262;
UPDATE `dbscript_string` SET `content_loc8`='Госпожа, передай Штоппору, что я хочу больше эля. Мне этого мало!' WHERE `entry` = 2000000263;
UPDATE `dbscript_string` SET `content_loc8`='Эй, Наг, как насчет того чтобы отрезать кусочек...' WHERE `entry` = 2000000264;
UPDATE `dbscript_string` SET `content_loc8`='Ты $gполучил:получила; это!' WHERE `entry` = 2000000265;
UPDATE `dbscript_string` SET `content_loc8`='На подходе!' WHERE `entry` = 2000000266;
UPDATE `dbscript_string` SET `content_loc8`='Не волнуйся детка, я верну...' WHERE `entry` = 2000000267;
UPDATE `dbscript_string` SET `content_loc8`='%s расслабляет свою хватку на журнале, который сжимала.' WHERE `entry` = 2000000612;
UPDATE `dbscript_string` SET `content_loc8`='%s быстро пролистывает страницы большого тома.' WHERE `entry` = 2000000786;
UPDATE `dbscript_string` SET `content_loc8`='Какая ирония – вместо того чтобы сражаться бок о бок с Братством, силы Штормграда брошены на защиту города.' WHERE `entry` = 2000000787;
UPDATE `dbscript_string` SET `content_loc8`='И где умрет одни, воскреснет два!' WHERE `entry` = 2000000788;
UPDATE `dbscript_string` SET `content_loc8`='%s перебирает книги.' WHERE `entry` = 2000000789;
UPDATE `dbscript_string` SET `content_loc8`='Куда же я положил редакции Торговой Компании?' WHERE `entry` = 2000000790;
UPDATE `dbscript_string` SET `content_loc8`='Эй, Ворон...' WHERE `entry` = 2000000791;
UPDATE `dbscript_string` SET `content_loc8`='Да?' WHERE `entry` = 2000000792;
UPDATE `dbscript_string` SET `content_loc8`='Мы можем отдохнуть? Мои ноги болят и вон те существа меня пугают.' WHERE `entry` = 2000000793;
UPDATE `dbscript_string` SET `content_loc8`='Я не знаю, Джилл. Если Клейвен спустится вниз и увидит, как мы болтаем, нам конец!' WHERE `entry` = 2000000794;
UPDATE `dbscript_string` SET `content_loc8`='Клейвен платит мне слишком кома за уничтожение этих зомби, дронов... Я не знаю, Джилл. Если Клейвен спустится вниз и увидит, как мы болтаем, нам конец!' WHERE `entry` = 2000000795;
UPDATE `dbscript_string` SET `content_loc8`='Наверное, ты прав, Ворон. Лучше я вернусь на патрулирование...' WHERE `entry` = 2000000796;
UPDATE `dbscript_string` SET `content_loc8`='На старт. Внимание. Марш!' WHERE `entry` = 2000000613;
UPDATE `dbscript_string` SET `content_loc8`='Эй! Так не честно!' WHERE `entry` = 2000000614;
UPDATE `dbscript_string` SET `content_loc8`='Победа!' WHERE `entry` = 2000000615;
UPDATE `dbscript_string` SET `content_loc8`='Здесь не обошлось без жульничества!' WHERE `entry` = 2000000616;
UPDATE `dbscript_string` SET `content_loc8`='Хочешь еще гонку? Лучшие два из трех!' WHERE `entry` = 2000000617;
UPDATE `dbscript_string` SET `content_loc8`='Жаль бросать клиента, но есть места, где нам надо побывать, и покупатели, которых нам надо облапошить. Мы еще вернемся. Пока!' WHERE `entry` = 2000000400;
UPDATE `dbscript_string` SET `content_loc8`='Каравану Гизлтона требуются надежные охранники. Ищите нас к востоку от хижины Кормека, севернее деревни кентавров из клана Колкар.' WHERE `entry` = 2000000401;
UPDATE `dbscript_string` SET `content_loc8`='Пора бы каравану уже выйти! Мы скоро вернемся, но если ты не можешь ждать, ступай на север к хижине Кормека. Мы откроем там лавку где-то через час.' WHERE `entry` = 2000000402;
UPDATE `dbscript_string` SET `content_loc8`='Я Риггер Гизлтон. Мне нужны охранники для сопровождения каравана через Поле Маннорок. Ищите меня на дороге восточнее Деревни Ночных Охотников.' WHERE `entry` = 2000000403;
UPDATE `dbscript_string` SET `content_loc8`='Поговори со мной, если хочешь услышать мою историю.' WHERE `entry` = 2000000813;
UPDATE `dbscript_string` SET `content_loc8`='Приветствую вас, смертные! Я был активирован благодаря дискам Норганнона, чтобы помочь вам!' WHERE `entry` = 2000000817;
UPDATE `dbscript_string` SET `content_loc8`='Диски готовы! Чтобы извлечь их, используй диски Норганнона.' WHERE `entry` = 2000000818;
UPDATE `dbscript_string` SET `content_loc8`='Амаккар, как ты думаешь, куда собирается отправить нас полководец Клинозуб? Не уверен, что я смогу выдержать еще одно путешествие по степям.' WHERE `entry` = 2000000645;
UPDATE `dbscript_string` SET `content_loc8`='Хммм...' WHERE `entry` = 2000000646;
UPDATE `dbscript_string` SET `content_loc8`='Хватит вести себя как ребенок, Разал\'меч. Пришло время стать частью одной из элитных сил Вождя. Ты же не хочешь закончить как Гаргал, не так ли?' WHERE `entry` = 2000000647;
UPDATE `dbscript_string` SET `content_loc8`='%s не обращает внимание на комментарии.' WHERE `entry` = 2000000648;
UPDATE `dbscript_string` SET `content_loc8`='Гордый Клык!' WHERE `entry` = 2000000649;
UPDATE `dbscript_string` SET `content_loc8`='Нет, Гаргал. Нет.' WHERE `entry` = 2000000650;
UPDATE `dbscript_string` SET `content_loc8`='Но...' WHERE `entry` = 2000000651;
UPDATE `dbscript_string` SET `content_loc8`='Нет! Тссс! Просто заткнись. Полководец идет!' WHERE `entry` = 2000000652;
UPDATE `dbscript_string` SET `content_loc8`='%s смеется.' WHERE `entry` = 2000000653;
UPDATE `dbscript_string` SET `content_loc8`='Стройся, черви!' WHERE `entry` = 2000000654;
UPDATE `dbscript_string` SET `content_loc8`='Все здесь, сэр!' WHERE `entry` = 2000000655;
UPDATE `dbscript_string` SET `content_loc8`='Очень хорошо, Гордый Клык. Можете продолжать свой марш. Шевелись!' WHERE `entry` = 2000000656;
UPDATE `dbscript_string` SET `content_loc8`='Сэр, да сэр!' WHERE `entry` = 2000000657;
UPDATE `dbscript_string` SET `content_loc8`='Вы слышали полководца, черви! Марш!' WHERE `entry` = 2000000658;
UPDATE `dbscript_string` SET `content_loc8`='Ох, это ужасно, это просто ужасно! Вы сразу же УМРЕТЕ, когда увидите это, Вивиана.' WHERE `entry` = 2000000659;
UPDATE `dbscript_string` SET `content_loc8`='О, вот те на! Одной неопределенности достаточно, чтобы вызвать визг девчонки!' WHERE `entry` = 2000000660;
UPDATE `dbscript_string` SET `content_loc8`='Источник, из которого я слышала, новая эпидемия имеет ВЕСЬ букет предыдущей чумы, за исключением калорий или углеводов, старой чумы!' WHERE `entry` = 2000000661;
UPDATE `dbscript_string` SET `content_loc8`='%s взволновано хлопает.' WHERE `entry` = 2000000662;
UPDATE `dbscript_string` SET `content_loc8`='Ох, весьма восхитительно!' WHERE `entry` = 2000000663;
UPDATE `dbscript_string` SET `content_loc8`='Здравствуйте дамы. Слышали о новой чуме?' WHERE `entry` = 2000000664;
UPDATE `dbscript_string` SET `content_loc8`='Оууу... даже если бы ты были последним орком в Калимдоре, чурбан.' WHERE `entry` = 2000000665;
UPDATE `dbscript_string` SET `content_loc8`='%s краснеет.' WHERE `entry` = 2000000666;
UPDATE `dbscript_string` SET `content_loc8`='%s смеется.' WHERE `entry` = 2000000667;
UPDATE `dbscript_string` SET `content_loc8`='Эх, посмотрите на время! Я должен вернутся на пост...' WHERE `entry` = 2000000668;
UPDATE `dbscript_string` SET `content_loc8`='Прошу меня извинить, но мне нужно уходить. Удачного вам дня дамы.' WHERE `entry` = 2000000669;
UPDATE `dbscript_string` SET `content_loc8`='Ваше сообщение достигло нас, командир, но наше участие не санкционировано великим крестоносцем.' WHERE `entry` = 2000000618;
UPDATE `dbscript_string` SET `content_loc8`='Ваш лидер живет рядом с Наксрамасом. Думаете, он не чувствует давление?' WHERE `entry` = 2000000619;
UPDATE `dbscript_string` SET `content_loc8`='%s понижает свой голос до шепота.' WHERE `entry` = 2000000620;
UPDATE `dbscript_string` SET `content_loc8`='Даже демоны способны чувствовать страх...' WHERE `entry` = 2000000621;
UPDATE `dbscript_string` SET `content_loc8`='Активность Плети в Чумных землях увеличилась в десять раз. Мы получаем сообщения о нападениях Плети даже с таких дальних земель как Калимдор. Как, по вашему мнению, такое могло случиться? Как удалось Плети сделать то, что раньше считалось не возможным? Где теперь безопасно?' WHERE `entry` = 2000000622;
UPDATE `dbscript_string` SET `content_loc8`='Даже варвары будут вынуждены отреагировать. Орки, быко-люди...' WHERE `entry` = 2000000623;
UPDATE `dbscript_string` SET `content_loc8`='Таурены.' WHERE `entry` = 2000000624;
UPDATE `dbscript_string` SET `content_loc8`='Неважно. Отвратительная, неопрятная Ордынская нечисть...' WHERE `entry` = 2000000625;
UPDATE `dbscript_string` SET `content_loc8`='Вам не хватает тактичности, командир. И это не удивительно. Тем не менее, вы правы в том, что Орда будет вынуждена действовать. Но, не только Орда. Они уже пришли – герои со своего мира.' WHERE `entry` = 2000000626;
UPDATE `dbscript_string` SET `content_loc8`='Немного поздно. Плотина сломана. Мы всего лишь шишка на большой дороге.' WHERE `entry` = 2000000627;
UPDATE `dbscript_string` SET `content_loc8`='Так почему вы здесь? Что нам делать, если нет никакой надежды?' WHERE `entry` = 2000000628;
UPDATE `dbscript_string` SET `content_loc8`='Надежда существует... Испепелитель.' WHERE `entry` = 2000000629;
UPDATE `dbscript_string` SET `content_loc8`='Так это то, зачем вы пришли? Говорить о том, что послужило падением крестового похода? Этими словами вы открываете старые раны, командир!' WHERE `entry` = 2000000630;
UPDATE `dbscript_string` SET `content_loc8`='Испипелителя нет и другого не будет. Могрейн далек от того человека которым был его отец. И вы знаете это, командир! В конце концов, это ваше руководство несет ответственность за смерть лорда Могрейна.' WHERE `entry` = 2000000631;
UPDATE `dbscript_string` SET `content_loc8`='Именно вы манипулировали скорбящим ребенком, чтобы попытаться восстановить меч. Ребенок, который вырос в человека не имеющий в сердце ничего кроме мести и ненависти. И для чего? Вы сейчас к мечу не ближе чем даже пять лет назад.' WHERE `entry` = 2000000632;
UPDATE `dbscript_string` SET `content_loc8`='Тем не менее, вы думаете, что восстановление Испепелителя каким-то образом изменит ход битвы? Позвольте открыть вам маленький секрет, командир. Сила Испипелителя придет от того человека, который ей владеет... Я был там, командир. Я видел, как легионы нежити сгорели в праведном огне, прежде чем он обнажил клинок. Увы, вам не дано понять историю.' WHERE `entry` = 2000000633;
UPDATE `dbscript_string` SET `content_loc8`='А теперь замолчите и обратите внимание на то, где вы находитесь, либо я сообщу лорду Фордрингу и его рыцарям, что вы здесь не на мирной основе. Я уверен, он с большим удовольствием возьмется за ваше \"Искупление\".' WHERE `entry` = 2000000634;
UPDATE `dbscript_string` SET `content_loc8`='Вот ваше рыбное блюдо, командир. Наслаждайтесь!' WHERE `entry` = 2000000635;
UPDATE `dbscript_string` SET `content_loc8`='Отец, а вам фрукты? Верно?' WHERE `entry` = 2000000636;
UPDATE `dbscript_string` SET `content_loc8`='А дамам, жареный кабаненок. Наслаждайтесь!' WHERE `entry` = 2000000637;
UPDATE `dbscript_string` SET `content_loc8`='Передайте мои комплименты повару!' WHERE `entry` = 2000000638;
UPDATE `dbscript_string` SET `content_loc8`='Это манго? Превосходно!' WHERE `entry` = 2000000639;
UPDATE `dbscript_string` SET `content_loc8`='Спасибо, Джессика.' WHERE `entry` = 2000000640;
UPDATE `dbscript_string` SET `content_loc8`='Дайте мне знать если вам нужно будет что-то еще!' WHERE `entry` = 2000000641;
UPDATE `dbscript_string` SET `content_loc8`='Не могу не отметить что ваше платье очень прекрасно! Вы должны мне сказать, где вы его достали.' WHERE `entry` = 2000000642;
UPDATE `dbscript_string` SET `content_loc8`='Вправду... у вас очень красивое платье, Джессика.' WHERE `entry` = 2000000643;
UPDATE `dbscript_string` SET `content_loc8`='Дети Ночи, внемлите зову вашей королевы!' WHERE `entry` = 2000000500;
UPDATE `dbscript_string` SET `content_loc8`='Я приглашаю вас присоединиться к празднованию одной из самых почитаемых ночей – ночи, когда Отрекшиеся освободились от сдавливающих уз Плети!' WHERE `entry` = 2000000501;
UPDATE `dbscript_string` SET `content_loc8`='Именно в эту ночь, наши враги больше всего бояться нас. Именно в эту ночь, мы покажем нашим врагам, что означает, встать против Отрекшихся!' WHERE `entry` = 2000000502;
UPDATE `dbscript_string` SET `content_loc8`='Мы сжигаем Плетеного человека как символ нашей борьбы против тех, кто выступит против нас. Мы наносим пепел сожженного Плетеного человека как символ нашей бесконечной борьбы против тех, кто хотел бы поработить нас.' WHERE `entry` = 2000000503;
UPDATE `dbscript_string` SET `content_loc8`='Теперь же, пришло время сотрясти этот мир! Время, чтобы напомнить тем, кто желает поработить нас, что мы никогда не сдадимся!' WHERE `entry` = 2000000504;
UPDATE `dbscript_string` SET `content_loc8`='Теперь это время Отрекшихся! Власть Отрекшимся – раз и навсегда!' WHERE `entry` = 2000000505;
UPDATE `dbscript_string` SET `content_loc8`='Сжигание Плетеного человека начнется через тридцать минут! Приходите на фестиваль, который расположен к западу от Подгорода! Празднуйте Тыквовин и наше освобождение от Плети!' WHERE `entry` = 2000000508;
UPDATE `dbscript_string` SET `content_loc8`='Сжигание Плетеного человека начнется через пятнадцать минут! Приходите на фестиваль, который расположен к западу от Подгорода! Празднуйте Тыквовин и наше освобождение от Плети!' WHERE `entry` = 2000000509;
UPDATE `dbscript_string` SET `content_loc8`='Сжигание Плетеного человека начнется через пять минут! Приходите на фестиваль, который расположен к западу от Подгорода! Празднуйте Тыквовин и наше освобождение от Плети!' WHERE `entry` = 2000000510;
UPDATE `dbscript_string` SET `content_loc8`='Фестиваль Плетеного человека начинается! Власть Отрекшимся!' WHERE `entry` = 2000000511;
UPDATE `dbscript_string` SET `content_loc8`='Ах, свобода! Так сладка и так коротка...' WHERE `entry` = 2000005024;
UPDATE `dbscript_string` SET `content_loc8`='Что ж, долг зовет, да? Первое, колокол... придаст тебе силу!' WHERE `entry` = 2000005038;
UPDATE `dbscript_string` SET `content_loc8`='Продолжим. Теперь я положу диск... чтобы защитить тебя от урона.' WHERE `entry` = 2000005050;
UPDATE `dbscript_string` SET `content_loc8`='И, наконец, свеча... сожжет всех тех, кто посмеет помешать тебе!' WHERE `entry` = 2000005350;
UPDATE `dbscript_string` SET `content_loc8`='Вот и все, $N, мой долг исполнен и теперь я ухожу. Удачи тебе и не забудь за колокол, диск и свечу!' WHERE `entry` = 2000005351;
UPDATE `dbscript_string` SET `content_loc8`='А вот и мы! Что ж, приступим к работе или... ?' WHERE `entry` = 2000005352;
UPDATE `dbscript_string` SET `content_loc8`='Верно! Сюда...' WHERE `entry` = 2000005353;
UPDATE `dbscript_string` SET `content_loc8`='И так... последний шаг!' WHERE `entry` = 2000005178;
UPDATE `dbscript_string` SET `content_loc8`='Все, пергамент готов. Теперь, возвращайся к Горзиеки...' WHERE `entry` = 2000005179;
UPDATE `dbscript_string` SET `content_loc8`='Наконец они проявляют милосердие! Они дали нам выпить!' WHERE `entry` = 2000001033;
UPDATE `dbscript_string` SET `content_loc8`='И землекопский портер тоже дали! Хвала Свету! Я чуть не умер от жажды.' WHERE `entry` = 2000001034;
UPDATE `dbscript_string` SET `content_loc8`='Граждане Альянса! Владыка Черной горы повержен! $N и $Gего:ее; союзники, объединив усилия, одолели Нефариана!' WHERE `entry` = 2000001037;
UPDATE `dbscript_string` SET `content_loc8`='Воспряньте же духом! Соберитесь вокруг $Gсвоего защитника:своей защитницы;, грейтесь в лучах $Gего:ее; славы! Радостно восславьте $Gпобедителя:победительницу; дракона!' WHERE `entry` = 2000001038;
UPDATE `dbscript_string` SET `content_loc8`='НЕФАРИАН УБИТ! Жители Оргриммара, вот $N, склонитесь же перед $Gего:ее; мощью и силой $Gего:ее; союзников! Ведь удар, который они нанесли черным драконам, навсегда отвратит Аспектов от путей зла! Смертокрыл надолго запомнит это поражение – он стонет от горя и проклинает судьбу!' WHERE `entry` = 2000001035;
UPDATE `dbscript_string` SET `content_loc8`='$N $Gпреуспел:преуспела;! Нас ждет удача! Внемлите боевому кличу!' WHERE `entry` = 2000001036;
UPDATE `dbscript_string` SET `content_loc8`='Кошмар Урсала окончен! Мы свободны!' WHERE `entry` = 2000005012;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает ритуал.' WHERE `entry` = 2000001116;
UPDATE `dbscript_string` SET `content_loc8`='%s собирает материалы и начинает работать.' WHERE `entry` = 2000001117;
UPDATE `dbscript_string` SET `content_loc8`='Работа над оружием завершена, $N.' WHERE `entry` = 2000001118;
UPDATE `dbscript_string` SET `content_loc8`='Приступим к работе, $n!' WHERE `entry` = 2000001143;
UPDATE `dbscript_string` SET `content_loc8`='Я благодарю Свет за это благословение. Пусть же оно используется во имя справедливости и защиту всех добрых существ.' WHERE `entry` = 2000001144;
UPDATE `dbscript_string` SET `content_loc8`='Вот ты где, $n.' WHERE `entry` = 2000001145;
UPDATE `dbscript_string` SET `content_loc8`='Мы обречены!' WHERE `entry` = 2000000060;
UPDATE `dbscript_string` SET `content_loc8`='%s начинает применять заклинание призыва...' WHERE `entry` = 2000005521;
UPDATE `dbscript_string` SET `content_loc8`='Иди за мной, $N. Я скоро начну...' WHERE `entry` = 2000005522;